#ifndef IRODS_TABLE_COLUMN_KEY_MAPS_HPP
#define IRODS_TABLE_COLUMN_KEY_MAPS_HPP

#include <map>
#include <tuple>
#include <string>
#include <string_view>
#include <vector>

namespace irods::experimental::api::genquery
{
    const std::map<std::string, std::tuple<std::string, int>> table_alias_cycler_map{
        {"R_USER_PASSWORD", {"R_USER_PASSWORD", 0}},
        {"R_USER_SESSION_KEY", {"R_USER_SESSION_KEY", 0}},
        {"R_TOKN_MAIN", {"R_TOKN_MAIN", 0}},
        {"R_RESC_GROUP", {"R_RESC_GROUP", 0}},
        {"R_ZONE_MAIN", {"R_ZONE_MAIN", 0}},
        {"R_RESC_MAIN", {"R_RESC_MAIN", 0}},
        {"R_COLL_MAIN", {"R_COLL_MAIN", 0}},
        {"R_DATA_MAIN", {"R_DATA_MAIN", 0}},

        {"r_met2_main", {"R_META_MAIN r_met2_main" , 0}},
        {"R_META_MAIN", {"R_META_MAIN" , 0}},

        {"R_RULE_MAIN", {"R_RULE_MAIN", 0}},
        {"R_USER_MAIN", {"R_USER_MAIN", 0}},
        {"r_resc_access", {"R_OBJT_ACCESS r_resc_access", 0}},
        {"r_coll_access", {"R_OBJT_ACCESS r_coll_access", 0}},
        {"r_data_access", {"R_OBJT_ACCESS r_data_access", 0}},
        {"r_met2_access", {"R_OBJT_ACCESS r_met2_access", 0}},
        {"r_rule_access", {"R_OBJT_ACCESS r_rule_access", 0}},
        {"r_msrvc_access", {"R_OBJT_ACCESS r_msrvc_access", 0}},
        {"r_resc_audit", {"R_OBJT_AUDIT r_resc_audit", 0}},
        {"r_coll_audit", {"R_OBJT_AUDIT r_coll_audit", 0}},
        {"r_data_audit", {"R_OBJT_AUDIT r_data_audit", 0}},
        {"r_met2_audit", {"R_OBJT_AUDIT r_met2_audit", 0}},
        {"r_rule_audit", {"R_OBJT_AUDIT r_rule_audit", 0}},
        {"r_resc_deny_access", {"R_OBJT_DENY_ACCESS r_resc_deny_access", 0}},
        {"r_coll_deny_access", {"R_OBJT_DENY_ACCESS r_coll_deny_access", 0}},
        {"r_data_deny_access", {"R_OBJT_DENY_ACCESS r_data_deny_access", 0}},
        {"r_met2_deny_access", {"R_OBJT_DENY_ACCESS r_met2_deny_access", 0}},
        {"r_rule_deny_access", {"R_OBJT_DENY_ACCESS r_rule_deny_access", 0}},
        {"r_resc_metamap", {"R_OBJT_METAMAP r_resc_metamap", 0}},
        {"r_resc_grp_metamap", {"R_OBJT_METAMAP r_resc_grp_metamap", 0}},
        {"r_coll_metamap", {"R_OBJT_METAMAP r_coll_metamap", 0}},
        {"r_data_metamap", {"R_OBJT_METAMAP r_data_metamap", 0}},
        {"r_met2_metamap", {"R_OBJT_METAMAP r_met2_metamap", 0}},
        {"r_rule_metamap", {"R_OBJT_METAMAP r_rule_metamap", 0}},
        {"r_msrvc_metamap", {"R_OBJT_METAMAP r_msrvc_metamap", 0}},
        {"r_user_metamap", {"R_OBJT_METAMAP r_user_metamap", 0}},
        {"r_resc_user_group", {"R_USER_GROUP r_resc_user_group", 0}},
        {"r_coll_user_group", {"R_USER_GROUP r_coll_user_group", 0}},
        {"r_data_user_group", {"R_USER_GROUP r_data_user_group", 0}},
        {"r_met2_user_group", {"R_USER_GROUP r_met2_user_group", 0}},
        {"r_rule_user_group", {"R_USER_GROUP r_rule_user_group", 0}},
        {"r_resc_da_user_group", {"R_USER_GROUP r_resc_da_user_group", 0}},
        {"r_coll_da_user_group", {"R_USER_GROUP r_coll_da_user_group", 0}},
        {"r_data_da_user_group", {"R_USER_GROUP r_data_da_user_group", 0}},
        {"r_met2_da_user_group", {"R_USER_GROUP r_met2_da_user_group", 0}},
        {"r_rule_da_user_group", {"R_USER_GROUP r_rule_da_user_group", 0}},

        {"r_resc_au_user_group", {"R_USER_GROUP r_resc_au_user_group", 0}},
        {"r_coll_au_user_group", {"R_USER_GROUP r_coll_au_user_group", 0}},
        {"r_data_au_user_group", {"R_USER_GROUP r_data_au_user_group", 0}},
        {"r_met2_au_user_group", {"R_USER_GROUP r_met2_au_user_group", 0}},
        {"r_rule_au_user_group", {"R_USER_GROUP r_rule_au_user_group", 0}},
        {"r_resc_user_main", {"R_USER_MAIN r_resc_user_main", 0}},
        {"r_coll_user_main", {"R_USER_MAIN r_coll_user_main", 0}},
        {"r_data_user_main", {"R_USER_MAIN r_data_user_main", 0}},
        {"r_met2_user_main", {"R_USER_MAIN r_met2_user_main", 0}},
        {"r_rule_user_main", {"R_USER_MAIN r_rule_user_main", 0}},
        {"r_resc_da_user_main", {"R_USER_MAIN r_resc_da_user_main", 0}},
        {"r_coll_da_user_main", {"R_USER_MAIN r_coll_da_user_main", 0}},
        {"r_data_da_user_main", {"R_USER_MAIN r_data_da_user_main", 0}},
        {"r_met2_da_user_main", {"R_USER_MAIN r_met2_da_user_main", 0}},
        {"r_rule_da_user_main", {"R_USER_MAIN r_rule_da_user_main", 0}},
        {"r_resc_au_user_main", {"R_USER_MAIN r_resc_au_user_main", 0}},
        {"r_coll_au_user_main", {"R_USER_MAIN r_coll_au_user_main", 0}},
        {"r_data_au_user_main", {"R_USER_MAIN r_data_au_user_main", 0}},
        {"r_met2_au_user_main", {"R_USER_MAIN r_met2_au_user_main", 0}},
        {"r_rule_au_user_main", {"R_USER_MAIN r_rule_au_user_main", 0}},

        {"r_quota_user_main", {"R_USER_MAIN r_quota_user_main", 1}},
        {"r_quota_user_group", {"R_USER_MAIN r_quota_user_group", 1}},
        {"r_quota_resc_main", {"R_RESC_MAIN r_quota_resc_main", 1}},

        {"r_resc_tokn_accs", {"R_TOKN_MAIN r_resc_tokn_accs", 0}},
        {"r_coll_tokn_accs", {"R_TOKN_MAIN r_coll_tokn_accs", 0}},
        {"r_data_tokn_accs", {"R_TOKN_MAIN r_data_tokn_accs", 0}},

        {"r_rule_tokn_accs", {"R_TOKN_MAIN r_rule_tokn_accs", 0}},
        {"r_met2_tokn_accs", {"R_TOKN_MAIN r_met2_tokn_accs", 0}},
        {"r_resc_tokn_deny_accs", {"R_TOKN_MAIN r_resc_tokn_deny_accs", 0}},
        {"r_coll_tokn_deny_accs", {"R_TOKN_MAIN r_coll_tokn_deny_accs", 0}},
        {"r_data_tokn_deny_accs", {"R_TOKN_MAIN r_data_tokn_deny_accs", 0}},
        {"r_rule_tokn_deny_accs", {"R_TOKN_MAIN r_rule_tokn_deny_accs", 0}},
        {"r_met2_tokn_deny_accs", {"R_TOKN_MAIN r_met2_tokn_deny_accs", 0}},
        {"r_resc_tokn_audit", {"R_TOKN_MAIN r_resc_tokn_audit", 0}},
        {"r_coll_tokn_audit", {"R_TOKN_MAIN r_coll_tokn_audit", 0}},
        {"r_data_tokn_audit", {"R_TOKN_MAIN r_data_tokn_audit", 0}},
        {"r_rule_tokn_audit", {"R_TOKN_MAIN r_rule_tokn_audit", 0}},
        {"r_met2_tokn_audit", {"R_TOKN_MAIN r_met2_tokn_audit", 0}},
        {"r_resc_meta_main", {"R_META_MAIN r_resc_meta_main", 0}},
        {"r_resc_grp_meta_main", {"R_META_MAIN r_resc_grp_meta_main", 0}},
        {"r_coll_meta_main", {"R_META_MAIN r_coll_meta_main", 0}},
        {"r_data_meta_main", {"R_META_MAIN r_data_meta_main", 0}},
        {"r_rule_meta_main", {"R_META_MAIN r_rule_meta_main", 0}},
        {"r_user_meta_main", {"R_META_MAIN r_user_meta_main", 0}},
        {"r_met2_meta_main", {"R_META_MAIN r_met2_meta_main", 0}},

        {"R_USER_GROUP", {"R_USER_GROUP", 0}},
        {"r_group_main", {"R_USER_MAIN r_group_main", 0}},

        {"R_RULE_EXEC", {"R_RULE_EXEC", 0}},

        {"R_OBJT_AUDIT", {"R_OBJT_AUDIT", 0}},

        {"R_SERVER_LOAD", {"R_SERVER_LOAD", 0}},

        {"R_SERVER_LOAD_DIGEST", {"R_SERVER_LOAD_DIGEST", 0}},

        {"R_USER_AUTH", {"R_USER_AUTH", 0}},

        {"R_RULE_BASE_MAP", {"R_RULE_BASE_MAP", 0}},
        {"R_RULE_DVM_MAP", {"R_RULE_DVM_MAP", 0}},
        {"R_RULE_FNM_MAP", {"R_RULE_FNM_MAP", 0}},
        {"R_RULE_DVM", {"R_RULE_DVM", 0}},
        {"R_RULE_FNM", {"R_RULE_FNM", 0}},

        {"R_QUOTA_MAIN", {"R_QUOTA_MAIN", 0}},
        {"R_QUOTA_USAGE", {"R_QUOTA_USAGE", 0}},

        {"R_MICROSRVC_MAIN", {"R_MICROSRVC_MAIN", 0}},
        {"R_MICROSRVC_VER", {"R_MICROSRVC_VER", 0}},

        {"r_msrvc_deny_access", {"R_OBJT_DENY_ACCESS r_msrvc_deny_access", 0}},
        {"r_msrvc_audit", {"R_OBJT_AUDIT r_msrvc_audit", 0}},
        {"r_msrvc_meta_main", {"R_META_MAIN r_msrvc_meta_main", 0}},
        {"r_msrvc_tokn_accs", {"R_TOKN_MAIN r_msrvc_tokn_accs", 0}},
        {"r_msrvc_user_group", {"R_USER_GROUP r_msrvc_user_group", 0}},
        {"r_msrvc_user_main", {"R_USER_MAIN r_msrvc_user_main", 0}},
        {"r_msrvc_tokn_deny_accs", {"R_TOKN_MAIN r_msrvc_tokn_deny_accs", 0}},
        {"r_msrvc_da_user_group", {"R_USER_GROUP r_msrvc_da_user_group", 0}},
        {"r_msrvc_da_user_main", {"R_USER_MAIN r_msrvc_da_user_main", 0}},
        {"r_msrvc_tokn_audit", {"R_TOKN_MAIN r_msrvc_tokn_audit", 0}},
        {"r_msrvc_au_user_group", {"R_USER_GROUP r_msrvc_au_user_group", 0}},
        {"r_msrvc_au_user_main", {"R_USER_MAIN r_msrvc_au_user_main", 0}},

        {"R_TICKET_MAIN", {"R_TICKET_MAIN", 0}},
        {"R_TICKET_ALLOWED_HOSTS", {"R_TICKET_ALLOWED_HOSTS", 0}},
        {"R_TICKET_ALLOWED_USERS", {"R_TICKET_ALLOWED_USERS", 0}},
        {"R_TICKET_ALLOWED_GROUPS", {"R_TICKET_ALLOWED_GROUPS", 0}},
        {"r_ticket_coll_main", {"R_COLL_MAIN r_ticket_coll_main", 1}},
        {"r_ticket_user_main", {"R_USER_MAIN r_ticket_user_main", 1}},
        {"r_ticket_data_coll_main", {"R_COLL_MAIN r_ticket_data_coll_main", 1}}
    }; // table alias cycler map

    // Maps the General Query names to the database tables and columns.

    struct column_info
    {
        std::string table;
        std::string name;
    };

    const std::map<std::string, column_info> column_name_mappings{
        {"ZONE_ID",          {"R_ZONE_MAIN", "zone_id"}},
        {"ZONE_NAME",        {"R_ZONE_MAIN", "zone_name"}},
        {"ZONE_TYPE",        {"R_ZONE_MAIN", "zone_type_name"}},
        {"ZONE_CONNECTION",  {"R_ZONE_MAIN", "zone_conn_string"}},
        {"ZONE_COMMENT",     {"R_ZONE_MAIN", "r_comment"}},
        {"ZONE_CREATE_TIME", {"R_ZONE_MAIN", "create_ts"}},
        {"ZONE_MODIFY_TIME", {"R_ZONE_MAIN", "modify_ts"}},

        {"USER_ID",          {"R_USER_MAIN", "user_id"}},
        {"USER_NAME",        {"R_USER_MAIN", "user_name"}},
        {"USER_TYPE",        {"R_USER_MAIN", "user_type_name"}},
        {"USER_ZONE",        {"R_USER_MAIN", "zone_name"}},
        {"USER_INFO",        {"R_USER_MAIN", "user_info"}},
        {"USER_COMMENT",     {"R_USER_MAIN", "r_comment"}},
        {"USER_CREATE_TIME", {"R_USER_MAIN", "create_ts"}},
        {"USER_MODIFY_TIME", {"R_USER_MAIN", "modify_ts"}},
        {"USER_AUTH_ID",     {"R_USER_AUTH", "user_id"}},
        {"USER_DN",          {"R_USER_AUTH", "user_auth_name"}},
        {"USER_DN_INVALID",  {"R_USER_MAIN", "r_comment"}}, // For compatibility.

        {"RESC_ID",             {"R_RESC_MAIN", "resc_id"}},
        {"RESC_NAME",           {"R_RESC_MAIN", "resc_name"}},
        {"ZONE_NAME",           {"R_RESC_MAIN", "zone_name"}},
        {"TYPE_NAME",           {"R_RESC_MAIN", "resc_type_name"}},
        {"CLASS_NAME",          {"R_RESC_MAIN", "resc_class_name"}},
        {"LOC",                 {"R_RESC_MAIN", "resc_net"}}, // TODO RESC_HOSTNAME?
        {"VAULT_PATH",          {"R_RESC_MAIN", "resc_def_path "}},
        {"FREE_SPACE",          {"R_RESC_MAIN", "free_space"}},
        {"FREE_SPACE_TIME",     {"R_RESC_MAIN", "free_space_ts"}},
        {"RESC_INFO",           {"R_RESC_MAIN", "resc_info"}},
        {"RESC_COMMENT",        {"R_RESC_MAIN", "r_comment"}},
        {"RESC_STATUS",         {"R_RESC_MAIN", "resc_status"}},
        {"CREATE_TIME",         {"R_RESC_MAIN", "create_ts"}},
        {"RESC_MODIFY_TIME",    {"R_RESC_MAIN", "modify_ts "}},
        {"RESC_CHILDREN",       {"R_RESC_MAIN", "resc_children "}},
        {"RESC_CONTEXT",        {"R_RESC_MAIN", "resc_context "}},
        {"RESC_PARENT",         {"R_RESC_MAIN", "resc_parent "}},
        {"RESC_PARENT_CONTEXT", {"R_RESC_MAIN", "resc_parent_context"}},
        {"DATA_ID",             {"R_DATA_MAIN", "data_id"}},
        {"COLL_ID",             {"R_DATA_MAIN", "coll_id"}},
        {"DATA_NAME",           {"R_DATA_MAIN", "data_name"}},
        {"DATA_REPL_NUM",       {"R_DATA_MAIN", "data_repl_num"}},
        {"DATA_VERSION",        {"R_DATA_MAIN", "data_version"}},
        {"DATA_TYPE_NAME",      {"R_DATA_MAIN", "data_type_name"}},
        {"DATA_SIZE",           {"R_DATA_MAIN", "data_size"}},
        {"DATA_PATH",           {"R_DATA_MAIN", "data_path"}},
        {"OWNER_NAME",          {"R_DATA_MAIN", "data_owner_name"}},
        {"OWNER_ZONE",          {"R_DATA_MAIN", "data_owner_zone"}},
        {"DATA_REPL_STATUS",    {"R_DATA_MAIN", "data_is_dirty"}},
        {"DATA_STATUS",         {"R_DATA_MAIN", "data_status"}},
        {"DATA_CHECKSUM",       {"R_DATA_MAIN", "data_checksum"}},
        {"EXPIRY",              {"R_DATA_MAIN", "data_expiry_ts"}},
        {"MAP_ID",              {"R_DATA_MAIN", "data_map_id"}},
        {"COMMENTS",            {"R_DATA_MAIN", "r_comment"}},
        {"CREATE_TIME",         {"R_DATA_MAIN", "create_ts"}},
        {"DATA_MODIFY_TIME",    {"R_DATA_MAIN", "modify_ts"}},
        {"DATA_MODE",           {"R_DATA_MAIN", "data_mode"}},
        {"DATA_RESC_ID",        {"R_DATA_MAIN", "resc_id"}},
        {"DATA_USER_NAME",      {"R_USER_MAIN", "user_name"}},
        {"DATA_USER_ZONE",      {"R_USER_MAIN", "zone_name"}},

        {"COLL_ID",          {"R_COLL_MAIN", "coll_id"}},
        {"COLL_NAME",        {"R_COLL_MAIN", "coll_name"}},
        {"COLL_PARENT_NAME", {"R_COLL_MAIN", "parent_coll_name"}},
        {"COLL_OWNER_NAME",  {"R_COLL_MAIN", "coll_owner_name"}},
        {"COLL_OWNER_ZONE",  {"R_COLL_MAIN", "coll_owner_zone"}},
        {"COLL_MAP_ID",      {"R_COLL_MAIN", "coll_map_id"}},
        {"COLL_INHERITANCE", {"R_COLL_MAIN", "coll_inheritance"}},
        {"COLL_COMMENTS",    {"R_COLL_MAIN", "r_comment"}},
        {"COLL_CREATE_TIME", {"R_COLL_MAIN", "create_ts"}},
        {"COLL_MODIFY_TIME", {"R_COLL_MAIN", "modify_ts"}},
        {"COLL_TYPE",        {"R_COLL_MAIN", "coll_type"}},
        {"COLL_INFO1",       {"R_COLL_MAIN", "coll_info1"}},
        {"COLL_INFO2",       {"R_COLL_MAIN", "coll_info2"}},

        {"META_DATA_ATTR_NAME",   {"R_META_MAIN_DATA", "meta_attr_name"}},
        {"META_DATA_ATTR_VALUE",  {"R_META_MAIN_DATA", "meta_attr_value"}},
        {"META_DATA_ATTR_UNITS",  {"R_META_MAIN_DATA", "meta_attr_unit"}},
        {"META_DATA_ATTR_ID",     {"R_META_MAIN_DATA", "meta_id"}},
        {"META_DATA_CREATE_TIME", {"R_META_MAIN_DATA", "create_ts"}},
        {"META_DATA_MODIFY_TIME", {"R_META_MAIN_DATA", "modify_ts"}},

        {"META_COLL_ATTR_NAME",   {"R_META_MAIN_COLL", "meta_attr_name"}},
        {"META_COLL_ATTR_VALUE",  {"R_META_MAIN_COLL", "meta_attr_value"}},
        {"META_COLL_ATTR_UNITS",  {"R_META_MAIN_COLL", "meta_attr_unit"}},
        {"META_COLL_ATTR_ID",     {"R_META_MAIN_COLL", "meta_id"}},
        {"META_COLL_CREATE_TIME", {"R_META_MAIN_COLL", "create_ts"}},
        {"META_COLL_MODIFY_TIME", {"R_META_MAIN_COLL", "modify_ts"}},

        {"META_RESC_ATTR_NAME",   {"R_META_MAIN_RESC", "meta_attr_name"}},
        {"META_RESC_ATTR_VALUE",  {"R_META_MAIN_RESC", "meta_attr_value"}},
        {"META_RESC_ATTR_UNITS",  {"R_META_MAIN_RESC", "meta_attr_unit"}},
        {"META_RESC_ATTR_ID",     {"R_META_MAIN_RESC", "meta_id"}},
        {"META_RESC_CREATE_TIME", {"R_META_MAIN_RESC", "create_ts"}},
        {"META_RESC_MODIFY_TIME", {"R_META_MAIN_RESC", "modify_ts"}},

        {"META_USER_ATTR_NAME",   {"R_META_MAIN_USER", "meta_attr_name"}},
        {"META_USER_ATTR_VALUE",  {"R_META_MAIN_USER", "meta_attr_value"}},
        {"META_USER_ATTR_UNITS",  {"R_META_MAIN_USER", "meta_attr_unit"}},
        {"META_USER_ATTR_ID",     {"R_META_MAIN_USER", "meta_id"}},
        {"META_USER_CREATE_TIME", {"R_META_MAIN_USER", "create_ts"}},
        {"META_USER_MODIFY_TIME", {"R_META_MAIN_USER", "modify_ts"}},

        // TODO What are these?
        //{"META_MET2_ATTR_NAME",   {"R_META_MAIN", "meta_attr_name"}},
        //{"META_MET2_ATTR_VALUE",  {"R_META_MAIN", "meta_attr_value"}},
        //{"META_MET2_ATTR_UNITS",  {"R_META_MAIN", "meta_attr_unit"}},
        //{"META_MET2_ATTR_ID",     {"R_META_MAIN", "meta_id"}},
        //{"META_MET2_CREATE_TIME", {"R_META_MAIN", "create_ts"}},
        //{"META_MET2_MODIFY_TIME", {"R_META_MAIN", "modify_ts"}},

        {"USER_GROUP_ID",   {"R_USER_GROUP", "group_user_id"}},
        {"USER_GROUP_NAME", {"R_USER_MAIN", "user_name"}},

        {"RULE_EXEC_ID",                 {"R_RULE_EXEC", "rule_exec_id"}},
        {"RULE_EXEC_NAME",               {"R_RULE_EXEC", "rule_name"}},
        {"RULE_EXEC_REI_FILE_PATH",      {"R_RULE_EXEC", "rei_file_path"}},
        {"RULE_EXEC_USER_NAME",          {"R_RULE_EXEC", "user_name"}},
        {"RULE_EXEC_ADDRESS",            {"R_RULE_EXEC", "exe_address"}},
        {"RULE_EXEC_TIME",               {"R_RULE_EXEC", "exe_time"}},
        {"RULE_EXEC_FREQUENCY",          {"R_RULE_EXEC", "exe_frequency"}},
        {"RULE_EXEC_PRIORITY",           {"R_RULE_EXEC", "priority"}},
        {"RULE_EXEC_ESTIMATED_EXE_TIME", {"R_RULE_EXEC", "estimated_exe_time"}},
        {"RULE_EXEC_NOTIFICATION_ADDR",  {"R_RULE_EXEC", "notification_addr"}},
        {"RULE_EXEC_LAST_EXE_TIME",      {"R_RULE_EXEC", "last_exe_time"}},
        {"RULE_EXEC_STATUS",             {"R_RULE_EXEC", "exe_status"}},

        {"TOKEN_NAMESPACE", {"R_TOKN_MAIN", "token_namespace"}},
        {"TOKEN_ID",        {"R_TOKN_MAIN", "token_id"}},
        {"TOKEN_NAME",      {"R_TOKN_MAIN", "token_name"}},
        {"TOKEN_VALUE",     {"R_TOKN_MAIN", "token_value"}},
        {"TOKEN_VALUE2",    {"R_TOKN_MAIN", "token_value2"}},
        {"TOKEN_VALUE3",    {"R_TOKN_MAIN", "token_value3"}},
        {"TOKEN_COMMENT",   {"R_TOKN_MAIN", "r_comment"}},

        // TODO These likely need table alias?
        // What is the difference between COLL_USER_ZONE and COLL_ZONE_NAME?
        // Perhaps, COLL_USER_ZONE is the zone the user is part of while COLL_ZONE_NAME
        // is the zone name the collection is associated with.
        {"COLL_USER_NAME", {"R_USER_MAIN", "user_name"}},
        {"COLL_USER_ZONE", {"R_USER_MAIN", "zone_name"}},

        {"QUOTA_USER_ID",           {"R_QUOTA_MAIN", "user_id"}},
        {"QUOTA_RESC_ID",           {"R_QUOTA_MAIN", "resc_id"}},
        {"QUOTA_LIMIT",             {"R_QUOTA_MAIN", "quota_limit"}},
        {"QUOTA_OVER",              {"R_QUOTA_MAIN", "quota_over"}},
        {"QUOTA_MODIFY_TIME",       {"R_QUOTA_MAIN", "modify_ts"}},
        {"QUOTA_USAGE_USER_ID",     {"R_QUOTA_USAGE", "user_id"}},
        {"QUOTA_USAGE_RESC_ID",     {"R_QUOTA_USAGE", "resc_id"}},
        {"QUOTA_USAGE",             {"R_QUOTA_USAGE", "quota_usage"}},
        {"QUOTA_USAGE_MODIFY_TIME", {"R_QUOTA_USAGE", "modify_ts"}},
        // TODO Probably need aliases.
        {"QUOTA_USER_NAME",         {"R_USER_MAIN", "user_name"}},
        {"QUOTA_USER_TYPE",         {"R_USER_MAIN", "user_type_name"}},
        {"QUOTA_USER_ZONE",         {"R_USER_MAIN", "zone_name"}},
        {"QUOTA_RESC_NAME",         {"R_RESC_MAIN", "resc_name"}},

        {"DATA_ACCESS_TYPE",     {"R_OBJT_ACCESS_DATA", "access_type_id"}},
        {"DATA_ACCESS_USER_ID",  {"R_OBJT_ACCESS_DATA", "user_id"}},
        {"DATA_ACCESS_DATA_ID",  {"R_OBJT_ACCESS_DATA", "object_id"}},
        {"DATA_ACCESS_NAME",     {"R_TOKN_MAIN_DATA", "token_name"}},
        {"DATA_TOKEN_NAMESPACE", {"R_TOKN_MAIN_DATA", "token_namespace"}},

        {"COLL_ACCESS_TYPE",     {"R_OBJT_ACCESS_COLL", "access_type_id"}},
        {"COLL_ACCESS_USER_ID",  {"R_OBJT_ACCESS_COLL", "user_id"}},
        {"COLL_ACCESS_COLL_ID",  {"R_OBJT_ACCESS_COLL", "object_id"}},
        {"COLL_ACCESS_NAME",     {"R_TOKN_MAIN_COLL", "token_name"}},
        {"COLL_TOKEN_NAMESPACE", {"R_TOKN_MAIN_COLL", "token_namespace"}},

        {"TICKET_ID",                      {"R_TICKET_MAIN", "ticket_id"}},
        {"TICKET_STRING",                  {"R_TICKET_MAIN", "ticket_string"}},
        {"TICKET_TYPE",                    {"R_TICKET_MAIN", "ticket_type"}},
        {"TICKET_USER_ID",                 {"R_TICKET_MAIN", "user_id"}},
        {"TICKET_OBJECT_ID",               {"R_TICKET_MAIN", "object_id"}},
        {"TICKET_OBJECT_TYPE",             {"R_TICKET_MAIN", "object_type"}},
        {"TICKET_USES_LIMIT",              {"R_TICKET_MAIN", "uses_limit"}},
        {"TICKET_USES_COUNT",              {"R_TICKET_MAIN", "uses_count"}},
        {"TICKET_WRITE_FILE_LIMIT",        {"R_TICKET_MAIN", "write_file_limit"}},
        {"TICKET_WRITE_FILE_COUNT",        {"R_TICKET_MAIN", "write_file_count"}},
        {"TICKET_WRITE_BYTE_LIMIT",        {"R_TICKET_MAIN", "write_byte_limit"}},
        {"TICKET_WRITE_BYTE_COUNT",        {"R_TICKET_MAIN", "write_byte_count"}},
        {"TICKET_EXPIRY_TS",               {"R_TICKET_MAIN", "ticket_expiry_ts"}},
        {"TICKET_CREATE_TIME",             {"R_TICKET_MAIN", "create_time"}},
        {"TICKET_MODIFY_TIME",             {"R_TICKET_MAIN", "modify_time"}},
        {"TICKET_ALLOWED_HOST",            {"R_TICKET_ALLOWED_HOSTS", "host"}},
        {"TICKET_ALLOWED_HOST_TICKET_ID",  {"R_TICKET_ALLOWED_HOSTS", "ticket_id"}},
        {"TICKET_ALLOWED_USER_NAME",       {"R_TICKET_ALLOWED_USERS", "user_name"}},
        {"TICKET_ALLOWED_USER_TICKET_ID",  {"R_TICKET_ALLOWED_USERS", "ticket_id"}},
        {"TICKET_ALLOWED_GROUP_NAME",      {"R_TICKET_ALLOWED_GROUPS", "group_name"}},
        {"TICKET_ALLOWED_GROUP_TICKET_ID", {"R_TICKET_ALLOWED_GROUPS", "ticket_id"}},
        {"TICKET_DATA_NAME",               {"R_DATA_MAIN", "data_name"}},
        {"TICKET_COLL_NAME",               {"R_COLL_MAIN", "coll_name"}},
        {"TICKET_OWNER_NAME",              {"R_USER_MAIN", "user_name"}},
        {"TICKET_OWNER_ZONE",              {"R_USER_MAIN", "zone_name"}},
        {"TICKET_DATA_COLL_NAME",          {"R_COLL_MAIN", "coll_name"}} // Includes join between R_DATA_MAIN and R_COLL_MAIN.
    }; // column_table_alias_map

    const std::map<std::string_view, std::string_view> table_alias_map{
        {"R_META_MAIN_COLL",    "R_META_MAIN R_META_MAIN_COLL"},
        {"R_META_MAIN_DATA",    "R_META_MAIN R_META_MAIN_DATA"},
        {"R_META_MAIN_USER",    "R_META_MAIN R_META_MAIN_USER"},
        {"R_META_MAIN_RESC",    "R_META_MAIN R_META_MAIN_RESC"},
        {"R_OBJT_METAMAP_COLL", "R_OBJT_METAMAP R_OBJT_METAMAP_COLL"},
        {"R_OBJT_METAMAP_DATA", "R_OBJT_METAMAP R_OBJT_METAMAP_DATA"},
        {"R_OBJT_METAMAP_USER", "R_OBJT_METAMAP R_OBJT_METAMAP_USER"},
        {"R_OBJT_METAMAP_RESC", "R_OBJT_METAMAP R_OBJT_METAMAP_RESC"},
        {"R_OBJT_ACCESS_COLL",  "R_OBJT_ACCESS R_OBJT_ACCESS_COLL"},
        {"R_OBJT_ACCESS_DATA",  "R_OBJT_ACCESS R_OBJT_ACCESS_DATA"},
        {"R_TOKN_MAIN_COLL",    "R_TOKN_MAIN R_TOKN_MAIN_COLL"},
        {"R_TOKN_MAIN_DATA",    "R_TOKN_MAIN R_TOKN_MAIN_DATA"},
    }; // table_alias_map

    // Defines the foreign key links between tables.

    struct foreign_key_link
    {
        std::string table_a;
        std::string table_b;
        std::string join_condition;
    };

    const std::vector<foreign_key_link> foreign_key_link_map{
        {"R_COLL_MAIN", "R_DATA_MAIN", "R_COLL_MAIN.coll_id = R_DATA_MAIN.coll_id"},
        {"R_RESC_GROUP", "R_RESC_MAIN", "R_RESC_GROUP.resc_id = R_RESC_MAIN.resc_id"},
        {"R_RESC_MAIN", "r_resc_metamap", "R_RESC_MAIN.resc_id = r_resc_metamap.object_id"},
        {"R_RESC_MAIN", "R_DATA_MAIN", "R_RESC_MAIN.resc_id = R_DATA_MAIN.resc_id"},
        {"R_RESC_GROUP", "r_resc_grp_metamap", "R_RESC_GROUP.resc_group_id = r_resc_grp_metamap.object_id"},
        {"R_COLL_MAIN", "r_coll_metamap", "R_COLL_MAIN.coll_id = r_coll_metamap.object_id"},

        {"R_DATA_MAIN", "r_data_metamap", "R_DATA_MAIN.data_id = r_data_metamap.object_id"},

        {"R_RULE_MAIN", "r_rule_metamap", "R_RULE_MAIN.rule_id = r_rule_metamap.object_id"},
        {"R_USER_MAIN", "r_user_metamap", "R_USER_MAIN.user_id = r_user_metamap.object_id"},
        {"r_met2_main", "r_met2_metamap", "r_met2_main.meta_id = r_met2_metamap.object_id"},
        {"R_RESC_MAIN", "r_resc_access", "R_RESC_MAIN.resc_id = r_resc_access.object_id"},
        {"R_COLL_MAIN", "r_coll_access", "R_COLL_MAIN.coll_id = r_coll_access.object_id"},
        {"R_DATA_MAIN", "r_data_access", "R_DATA_MAIN.data_id = r_data_access.object_id"},
        {"R_RULE_MAIN", "r_rule_access", "R_RULE_MAIN.rule_id = r_rule_access.object_id"},
        {"r_met2_main", "r_met2_access", "r_met2_main.meta_id = r_met2_access.object_id"},
        {"R_RESC_MAIN", "r_resc_deny_access", "R_RESC_MAIN.resc_id = r_resc_deny_access.object_id"},
        {"R_COLL_MAIN", "r_coll_deny_access", "R_COLL_MAIN.coll_id = r_coll_deny_access.object_id"},
        {"R_DATA_MAIN", "r_data_deny_access", "R_DATA_MAIN.data_id = r_data_deny_access.object_id"},
        {"R_RULE_MAIN", "r_rule_deny_access", "R_RULE_MAIN.rule_id = r_rule_deny_access.object_id"},
        {"r_met2_main", "r_met2_deny_access", "r_met2_main.meta_id = r_met2_deny_access.object_id"},
        {"R_RESC_MAIN", "r_resc_audit", "R_RESC_MAIN.resc_id = r_resc_audit.object_id"},
        {"R_COLL_MAIN", "r_coll_audit", "R_COLL_MAIN.coll_id = r_coll_audit.object_id"},
        {"R_DATA_MAIN", "r_data_audit", "R_DATA_MAIN.data_id = r_data_audit.object_id"},
        {"R_RULE_MAIN", "r_rule_audit", "R_RULE_MAIN.rule_id = r_rule_audit.object_id"},
        {"r_met2_main", "r_met2_audit", "r_met2_main.meta_id = r_met2_audit.object_id.meta_id"},
        {"r_resc_metamap", "r_resc_meta_main",  "r_resc_metamap.meta_id = r_resc_meta_main.meta_id"},
        {"r_resc_grp_metamap", "r_resc_grp_meta_main",  "r_resc_grp_metamap.meta_id = r_resc_grp_meta_main.meta_id"},
        {"r_coll_metamap", "r_coll_meta_main",  "r_coll_metamap.meta_id = r_coll_meta_main.meta_id"},

        {"r_data_metamap", "r_data_meta_main",  "r_data_metamap.meta_id = r_data_meta_main.meta_id"},

        {"r_rule_metamap", "r_rule_meta_main",  "r_rule_metamap.meta_id = r_rule_meta_main.meta_id"},
        {"r_user_metamap", "r_user_meta_main",  "r_user_metamap.meta_id = r_user_meta_main.meta_id"},
        {"r_met2_metamap", "r_met2_meta_main",  "r_met2_metamap.object_id = r_met2_meta_main.meta_id"},
        {"r_resc_access", "r_resc_tokn_accs",  "r_resc_access.access_type_id = r_resc_tokn_accs.token_id"},
        {"r_resc_access", "r_resc_user_group", "r_resc_access.user_id = r_resc_user_group.group_user_id"},
        {"r_coll_access", "r_coll_tokn_accs",  "r_coll_access.access_type_id = r_coll_tokn_accs.token_id"},
        {"r_coll_access", "r_coll_user_group", "r_coll_access.user_id = r_coll_user_group.group_user_id"},
        {"r_data_access", "r_data_tokn_accs",  "r_data_access.access_type_id = r_data_tokn_accs.token_id"},
        {"r_data_access", "r_data_user_group", "r_data_access.user_id = r_data_user_group.group_user_id"},
        {"r_rule_access", "r_rule_tokn_accs",  "r_rule_access.access_typ_id = r_rule_tokn_accs.token_id"},
        {"r_rule_access", "r_rule_user_group", "r_rule_access.user_id = r_rule_user_group.group_user_id"},
        {"r_met2_access", "r_met2_tokn_accs",  "r_met2_access.access_typ_id = r_met2_tokn_accs.token_id"},
        {"r_met2_access", "r_met2_user_group", "r_met2_access.user_id = r_met2_user_group.group_user_id"},
        {"r_resc_deny_access", "r_resc_tokn_deny_accs", "r_resc_deny_access.access_typ_id = r_resc_tokn_deny_accs.token_id"},
        {"r_resc_deny_access", "r_resc_da_user_group",     "r_resc_deny_access.user_id = r_resc_da_user_group.group_user_id"},
        {"r_coll_deny_access", "r_coll_tokn_deny_accs", "r_coll_deny_access.access_typ_id = r_coll_tokn_deny_accs.token_id"},
        {"r_coll_deny_access", "r_coll_da_user_group",     "r_coll_deny_access.user_id = r_coll_da_user_group.group_user_id"},
        {"r_data_deny_access", "r_data_tokn_deny_accs", "r_data_deny_access.access_typ_id = r_data_tokn_deny_accs.token_id"},
        {"r_data_deny_access", "r_data_da_user_group",     "r_data_deny_access.user_id = r_data_da_user_group.group_user_id"},
        {"r_rule_deny_access", "r_rule_tokn_deny_accs", "r_rule_deny_access.access_typ_id = r_rule_tokn_deny_accs.token_id"},
        {"r_rule_deny_access", "r_rule_da_user_group",     "r_rule_deny_access.user_id = r_rule_da_user_group.group_user_id"},
        {"r_met2_deny_access", "r_met2_tokn_deny_accs", "r_met2_deny_access.access_typ_id = r_met2_tokn_deny_accs.token_id"},
        {"r_met2_deny_access", "r_met2_da_user_group",     "r_met2_deny_access.user_id = r_met2_da_user_group.group_user_id"},
        {"r_resc_audit", "r_resc_tokn_audit", "r_resc_audit.action_id = r_resc_tokn_audit.token_id"},
        {"r_resc_audit", "r_resc_au_user_group", "r_resc_audit.user_id = r_resc_au_user_group.group_user_id"},
        {"r_coll_audit", "r_coll_tokn_audit", "r_coll_audit.action_id = r_coll_tokn_audit.token_id"},
        {"r_coll_audit", "r_coll_au_user_group", "r_coll_audit.user_id = r_coll_au_user_group.group_user_id"},
        {"r_data_audit", "r_data_tokn_audit", "r_data_audit.action_id = r_data_tokn_audit.token_id"},
        {"r_data_audit", "r_data_au_user_group", "r_data_audit.user_id = r_data_au_user_group.group_user_id"},
        {"r_rule_audit", "r_rule_tokn_audit", "r_rule_audit.action_id = r_rule_tokn_audit.token_id"},
        {"r_rule_audit", "r_rule_au_user_group", "r_rule_audit.user_id = r_rule_au_user_group.group_user_id"},
        {"r_met2_audit", "r_met2_tokn_audit", "r_met2_audit.action_id = r_met2_tokn_audit.token_id"},
        {"r_met2_audit", "r_met2_au_user_group", "r_met2_audit.user_id = r_met2_au_user_group.group_user_id"},
        {"r_resc_user_group", "r_resc_user_main", "r_resc_user_group.user_id = r_resc_user_main.user_id"},
        {"r_coll_user_group", "r_coll_user_main", "r_coll_user_group.user_id = r_coll_user_main.user_id"},
        {"r_data_user_group", "r_data_user_main", "r_data_user_group.user_id = r_data_user_main.user_id"},
        {"r_rule_user_group", "r_rule_user_main", "r_rule_user_group.user_id = r_rule_user_main.user_id"},
        {"r_met2_user_group", "r_met2_user_main", "r_met2_user_group.user_id = r_met2_user_main.user_id"},
        {"r_resc_da_user_group", "r_resc_da_user_main", "r_resc_da_user_group.user_id = r_resc_da_user_main.user_id"},
        {"r_coll_da_user_group", "r_coll_da_user_main", "r_coll_da_user_group.user_id = r_coll_da_user_main.user_id"},
        {"r_data_da_user_group", "r_data_da_user_main", "r_data_da_user_group.user_id = r_data_da_user_main.user_id"},
        {"r_rule_da_user_group", "r_rule_da_user_main", "r_rule_da_user_group.user_id = r_rule_da_user_main.user_id"},
        {"r_met2_da_user_group", "r_met2_da_user_main", "r_met2_da_user_group.user_id = r_met2_da_user_main.user_id"},
        {"r_resc_au_user_group", "r_resc_au_user_main", "r_resc_au_user_group.user_id = r_resc_au_user_main.user_id"},
        {"r_coll_au_user_group", "r_coll_au_user_main", "r_coll_au_user_group.user_id = r_coll_au_user_main.user_id"},
        {"r_data_au_user_group", "r_data_au_user_main", "r_data_au_user_group.user_id = r_data_au_user_main.user_id"},
        {"r_rule_au_user_group", "r_rule_au_user_main", "r_rule_au_user_group.user_id = r_rule_au_user_main.user_id"},
        {"r_met2_au_user_group", "r_met2_au_user_main", "r_met2_au_user_group.user_id = r_met2_au_user_main.user_id"},
        {"R_USER_MAIN", "R_USER_PASSWORD", "R_USER_MAIN.user_id = R_USER_PASSWORD.user_id"},
        {"R_USER_MAIN", "R_USER_AUTH", "R_USER_MAIN.user_id = R_USER_AUTH.user_id"},
        {"R_USER_MAIN", "R_USER_SESSION_KEY", "R_USER_MAIN.user_id = R_USER_SESSION_KEY.user_id"},
        {"R_USER_MAIN", "r_data_access", "R_USER_MAIN.user_id = r_data_access.user_id"},
        {"R_USER_MAIN", "R_USER_GROUP", "R_USER_MAIN.user_id = R_USER_GROUP.user_id"},
        {"R_USER_GROUP", "r_group_main", "R_USER_GROUP.group_user_id = r_group_main.user_id"},
        {"R_USER_MAIN", "R_OBJT_AUDIT", "R_USER_MAIN.user_id = R_OBJT_AUDIT.user_id"},

        {"R_QUOTA_MAIN", "r_quota_user_main", "R_QUOTA_MAIN.user_id = r_quota_user_main.user_id"},
        {"R_QUOTA_MAIN", "r_quota_resc_main", "R_QUOTA_MAIN.resc_id = r_quota_resc_main.resc_id"},
        {"R_QUOTA_MAIN", "r_quota_user_group", "R_QUOTA_MAIN.user_id = r_quota_user_group.user_id"},
        {"R_QUOTA_USAGE", "r_quota_user_main", "R_QUOTA_USAGE.user_id = r_quota_user_main.user_id"},
        {"R_QUOTA_USAGE", "r_quota_resc_main", "R_QUOTA_USAGE.resc_id = r_quota_resc_main.resc_id"},
        {"R_QUOTA_USAGE", "r_quota_user_group", "R_QUOTA_USAGE.user_id = r_quota_user_group.user_id"},
        {"R_RULE_BASE_MAP", "R_RULE_MAIN", "R_RULE_BASE_MAP.rule_id = R_RULE_MAIN.rule_id"},
        {"R_RULE_DVM_MAP", "R_RULE_DVM", "R_RULE_DVM_MAP.dvm_id = R_RULE_DVM.dvm_id"},
        {"R_RULE_FNM_MAP", "R_RULE_FNM", "R_RULE_FNM_MAP.fnm_id = R_RULE_FNM.fnm_id"},

        {"R_MICROSRVC_MAIN", "R_MICROSRVC_VER", "R_MICROSRVC_MAIN.msrvc_id = R_MICROSRVC_VER.msrvc_id"},
        {"R_MICROSRVC_MAIN", "r_msrvc_metamap", "R_MICROSRVC_MAIN.msrvc_id = r_msrvc_metamap.object_id"},
        {"r_msrvc_metamap", "r_msrvc_meta_main",  "r_msrvc_metamap.meta_id = r_msrvc_meta_main.meta_id"},
        {"R_MICROSRVC_MAIN", "r_msrvc_access", "R_MICROSRVC_MAIN.msrvc_id = r_msrvc_access.object_id"},
        {"r_msrvc_access", "r_msrvc_tokn_accs",  "r_msrvc_access.access_typ_id = r_msrvc_tokn_accs.token_id"},
        {"r_msrvc_access", "r_msrvc_user_group", "r_msrvc_access.user_id = r_msrvc_user_group.group_user_id"},
        {"r_msrvc_user_group", "r_msrvc_user_main", "r_msrvc_user_group.user_id = r_msrvc_user_main.user_id"},
        {"R_MICROSRVC_MAIN", "r_msrvc_deny_access", "R_MICROSRVC_MAIN.msrvc_id = r_msrvc_deny_access.object_id"},
        {"r_msrvc_deny_access", "r_msrvc_tokn_deny_accs", "r_msrvc_deny_access.access_typ_id = r_msrvc_tokn_deny_accs.token_id"},
        {"r_msrvc_deny_access", "r_msrvc_da_user_group",     "r_msrvc_deny_access.user_id = r_msrvc_da_user_group.group_user_id"},
        {"r_msrvc_da_user_group", "r_msrvc_da_user_main", "r_msrvc_da_user_group.user_id = r_msrvc_da_user_main.user_id"},
        {"R_MICROSRVC_MAIN", "r_msrvc_audit", "R_MICROSRVC_MAIN.msrvc_id = r_msrvc_audit.object_id"},
        {"r_msrvc_audit", "r_msrvc_tokn_audit", "r_msrvc_audit.action_id = r_msrvc_tokn_audit.token_id"},
        {"r_msrvc_audit", "r_msrvc_au_user_group", "r_msrvc_audit.user_id = r_msrvc_au_user_group.group_user_id"},
        {"r_msrvc_au_user_group", "r_msrvc_au_user_main", "r_msrvc_au_user_group.user_id = r_msrvc_au_user_main.user_id"},

        {"R_TICKET_MAIN", "R_TICKET_ALLOWED_HOSTS", "R_TICKET_MAIN.ticket_id = R_TICKET_ALLOWED_HOSTS.ticket_id"},
        {"R_TICKET_MAIN", "R_TICKET_ALLOWED_USERS", "R_TICKET_MAIN.ticket_id = R_TICKET_ALLOWED_USERS.ticket_id"},
        {"R_TICKET_MAIN", "R_TICKET_ALLOWED_GROUPS", "R_TICKET_MAIN.ticket_id = R_TICKET_ALLOWED_GROUPS.ticket_id"},

        {"R_TICKET_MAIN", "R_DATA_MAIN", "R_TICKET_MAIN.object_id = R_DATA_MAIN.data_id"},
        {"R_TICKET_MAIN", "r_ticket_coll_main", "R_TICKET_MAIN.object_id = r_ticket_coll_main.coll_id"},
        {"R_TICKET_MAIN", "r_ticket_data_coll_main", "R_TICKET_MAIN.object_id = R_DATA_MAIN.data_id AND R_DATA_MAIN.coll_id = r_ticket_data_coll_main.coll_id"},
        {"R_TICKET_MAIN", "r_ticket_user_main", "R_TICKET_MAIN.user_id = r_ticket_user_main.user_id"}
    }; // foreign_key_link_map
} // namespace irods::experemental::api::genquery

#endif // IRODS_TABLE_COLUMN_KEY_MAPS_HPP
