#ifndef IRODS_TABLE_COLUMN_KEY_MAPS_HPP
#define IRODS_TABLE_COLUMN_KEY_MAPS_HPP

#include <map>
#include <tuple>
#include <string>
#include <vector>

namespace irods::experimental::api::genquery
{
    const std::map<std::string, std::tuple<std::string, int>> table_alias_cycler_map{
        {"R_USER_PASSWORD", {"R_USER_PASSWORD", 0 }},
        {"R_USER_SESSION_KEY", {"R_USER_SESSION_KEY", 0 }},
        {"R_TOKN_MAIN", {"R_TOKN_MAIN", 0 }},
        {"R_RESC_GROUP", {"R_RESC_GROUP", 0 }},
        {"R_ZONE_MAIN", {"R_ZONE_MAIN", 0 }},
        {"R_RESC_MAIN", {"R_RESC_MAIN", 0 }},
        {"R_COLL_MAIN", {"R_COLL_MAIN", 0 }},
        {"R_DATA_MAIN", {"R_DATA_MAIN", 0 }},

        {"r_met2_main", {"R_META_MAIN r_met2_main" , 0 }},
        {"R_META_MAIN", {"R_META_MAIN" , 0 }},

        {"R_RULE_MAIN", {"R_RULE_MAIN", 0 }},
        {"R_USER_MAIN", {"R_USER_MAIN", 0 }},
        {"r_resc_access", {"R_OBJT_ACCESS r_resc_access", 0 }},
        {"r_coll_access", {"R_OBJT_ACCESS r_coll_access", 0 }},
        {"r_data_access", {"R_OBJT_ACCESS r_data_access", 0 }},
        {"r_met2_access", {"R_OBJT_ACCESS r_met2_access", 0 }},
        {"r_rule_access", {"R_OBJT_ACCESS r_rule_access", 0 }},
        {"r_msrvc_access", {"R_OBJT_ACCESS r_msrvc_access", 0 }},
        {"r_resc_audit", {"R_OBJT_AUDIT r_resc_audit", 0 }},
        {"r_coll_audit", {"R_OBJT_AUDIT r_coll_audit", 0 }},
        {"r_data_audit", {"R_OBJT_AUDIT r_data_audit", 0 }},
        {"r_met2_audit", {"R_OBJT_AUDIT r_met2_audit", 0 }},
        {"r_rule_audit", {"R_OBJT_AUDIT r_rule_audit", 0 }},
        {"r_resc_deny_access", {"R_OBJT_DENY_ACCESS r_resc_deny_access", 0 }},
        {"r_coll_deny_access", {"R_OBJT_DENY_ACCESS r_coll_deny_access", 0 }},
        {"r_data_deny_access", {"R_OBJT_DENY_ACCESS r_data_deny_access", 0 }},
        {"r_met2_deny_access", {"R_OBJT_DENY_ACCESS r_met2_deny_access", 0 }},
        {"r_rule_deny_access", {"R_OBJT_DENY_ACCESS r_rule_deny_access", 0 }},
        {"r_resc_metamap", {"R_OBJT_METAMAP r_resc_metamap", 0 }},
        {"r_resc_grp_metamap", {"R_OBJT_METAMAP r_resc_grp_metamap", 0 }},
        {"r_coll_metamap", {"R_OBJT_METAMAP r_coll_metamap", 0 }},
        {"r_data_metamap", {"R_OBJT_METAMAP r_data_metamap", 0 }},
        {"r_met2_metamap", {"R_OBJT_METAMAP r_met2_metamap", 0 }},
        {"r_rule_metamap", {"R_OBJT_METAMAP r_rule_metamap", 0 }},
        {"r_msrvc_metamap", {"R_OBJT_METAMAP r_msrvc_metamap", 0 }},
        {"r_user_metamap", {"R_OBJT_METAMAP r_user_metamap", 0 }},
        {"r_resc_user_group", {"R_USER_GROUP r_resc_user_group", 0 }},
        {"r_coll_user_group", {"R_USER_GROUP r_coll_user_group", 0 }},
        {"r_data_user_group", {"R_USER_GROUP r_data_user_group", 0 }},
        {"r_met2_user_group", {"R_USER_GROUP r_met2_user_group", 0 }},
        {"r_rule_user_group", {"R_USER_GROUP r_rule_user_group", 0 }},
        {"r_resc_da_user_group", {"R_USER_GROUP r_resc_da_user_group", 0 }},
        {"r_coll_da_user_group", {"R_USER_GROUP r_coll_da_user_group", 0 }},
        {"r_data_da_user_group", {"R_USER_GROUP r_data_da_user_group", 0 }},
        {"r_met2_da_user_group", {"R_USER_GROUP r_met2_da_user_group", 0 }},
        {"r_rule_da_user_group", {"R_USER_GROUP r_rule_da_user_group", 0 }},

        {"r_resc_au_user_group", {"R_USER_GROUP r_resc_au_user_group", 0 }},
        {"r_coll_au_user_group", {"R_USER_GROUP r_coll_au_user_group", 0 }},
        {"r_data_au_user_group", {"R_USER_GROUP r_data_au_user_group", 0 }},
        {"r_met2_au_user_group", {"R_USER_GROUP r_met2_au_user_group", 0 }},
        {"r_rule_au_user_group", {"R_USER_GROUP r_rule_au_user_group", 0 }},
        {"r_resc_user_main", {"R_USER_MAIN r_resc_user_main", 0 }},
        {"r_coll_user_main", {"R_USER_MAIN r_coll_user_main", 0 }},
        {"r_data_user_main", {"R_USER_MAIN r_data_user_main", 0 }},
        {"r_met2_user_main", {"R_USER_MAIN r_met2_user_main", 0 }},
        {"r_rule_user_main", {"R_USER_MAIN r_rule_user_main", 0 }},
        {"r_resc_da_user_main", {"R_USER_MAIN r_resc_da_user_main", 0 }},
        {"r_coll_da_user_main", {"R_USER_MAIN r_coll_da_user_main", 0 }},
        {"r_data_da_user_main", {"R_USER_MAIN r_data_da_user_main", 0 }},
        {"r_met2_da_user_main", {"R_USER_MAIN r_met2_da_user_main", 0 }},
        {"r_rule_da_user_main", {"R_USER_MAIN r_rule_da_user_main", 0 }},
        {"r_resc_au_user_main", {"R_USER_MAIN r_resc_au_user_main", 0 }},
        {"r_coll_au_user_main", {"R_USER_MAIN r_coll_au_user_main", 0 }},
        {"r_data_au_user_main", {"R_USER_MAIN r_data_au_user_main", 0 }},
        {"r_met2_au_user_main", {"R_USER_MAIN r_met2_au_user_main", 0 }},
        {"r_rule_au_user_main", {"R_USER_MAIN r_rule_au_user_main", 0 }},

        {"r_quota_user_main", {"R_USER_MAIN r_quota_user_main", 1 }},
        {"r_quota_user_group", {"R_USER_MAIN r_quota_user_group", 1 }},
        {"r_quota_resc_main", {"R_RESC_MAIN r_quota_resc_main", 1 }},

        {"r_resc_tokn_accs", {"R_TOKN_MAIN r_resc_tokn_accs", 0 }},
        {"r_coll_tokn_accs", {"R_TOKN_MAIN r_coll_tokn_accs", 0 }},
        {"r_data_tokn_accs", {"R_TOKN_MAIN r_data_tokn_accs", 0 }},

        {"r_rule_tokn_accs", {"R_TOKN_MAIN r_rule_tokn_accs", 0 }},
        {"r_met2_tokn_accs", {"R_TOKN_MAIN r_met2_tokn_accs", 0 }},
        {"r_resc_tokn_deny_accs", {"R_TOKN_MAIN r_resc_tokn_deny_accs", 0 }},
        {"r_coll_tokn_deny_accs", {"R_TOKN_MAIN r_coll_tokn_deny_accs", 0 }},
        {"r_data_tokn_deny_accs", {"R_TOKN_MAIN r_data_tokn_deny_accs", 0 }},
        {"r_rule_tokn_deny_accs", {"R_TOKN_MAIN r_rule_tokn_deny_accs", 0 }},
        {"r_met2_tokn_deny_accs", {"R_TOKN_MAIN r_met2_tokn_deny_accs", 0 }},
        {"r_resc_tokn_audit", {"R_TOKN_MAIN r_resc_tokn_audit", 0 }},
        {"r_coll_tokn_audit", {"R_TOKN_MAIN r_coll_tokn_audit", 0 }},
        {"r_data_tokn_audit", {"R_TOKN_MAIN r_data_tokn_audit", 0 }},
        {"r_rule_tokn_audit", {"R_TOKN_MAIN r_rule_tokn_audit", 0 }},
        {"r_met2_tokn_audit", {"R_TOKN_MAIN r_met2_tokn_audit", 0 }},
        {"r_resc_meta_main", {"R_META_MAIN r_resc_meta_main", 0 }},
        {"r_resc_grp_meta_main", {"R_META_MAIN r_resc_grp_meta_main", 0 }},
        {"r_coll_meta_main", {"R_META_MAIN r_coll_meta_main", 0 }},
        {"r_data_meta_main", {"R_META_MAIN r_data_meta_main", 0 }},
        {"r_rule_meta_main", {"R_META_MAIN r_rule_meta_main", 0 }},
        {"r_user_meta_main", {"R_META_MAIN r_user_meta_main", 0 }},
        {"r_met2_meta_main", {"R_META_MAIN r_met2_meta_main", 0 }},

        {"R_USER_GROUP", {"R_USER_GROUP", 0 }},
        {"r_group_main", {"R_USER_MAIN r_group_main", 0 }},

        {"R_RULE_EXEC", {"R_RULE_EXEC", 0 }},

        {"R_OBJT_AUDIT", {"R_OBJT_AUDIT", 0 }},

        {"R_SERVER_LOAD", {"R_SERVER_LOAD", 0 }},

        {"R_SERVER_LOAD_DIGEST", {"R_SERVER_LOAD_DIGEST", 0 }},

        {"R_USER_AUTH", {"R_USER_AUTH", 0 }},

        {"R_RULE_BASE_MAP", {"R_RULE_BASE_MAP", 0 }},
        {"R_RULE_DVM_MAP", {"R_RULE_DVM_MAP", 0 }},
        {"R_RULE_FNM_MAP", {"R_RULE_FNM_MAP", 0 }},
        {"R_RULE_DVM", {"R_RULE_DVM", 0 }},
        {"R_RULE_FNM", {"R_RULE_FNM", 0 }},

        {"R_QUOTA_MAIN", {"R_QUOTA_MAIN", 0 }},
        {"R_QUOTA_USAGE", {"R_QUOTA_USAGE", 0 }},

        {"R_MICROSRVC_MAIN", {"R_MICROSRVC_MAIN", 0 }},
        {"R_MICROSRVC_VER", {"R_MICROSRVC_VER", 0 }},

        {"r_msrvc_deny_access", {"R_OBJT_DENY_ACCESS r_msrvc_deny_access", 0 }},
        {"r_msrvc_audit", {"R_OBJT_AUDIT r_msrvc_audit", 0 }},
        {"r_msrvc_meta_main", {"R_META_MAIN r_msrvc_meta_main", 0 }},
        {"r_msrvc_tokn_accs", {"R_TOKN_MAIN r_msrvc_tokn_accs", 0 }},
        {"r_msrvc_user_group", {"R_USER_GROUP r_msrvc_user_group", 0 }},
        {"r_msrvc_user_main", {"R_USER_MAIN r_msrvc_user_main", 0 }},
        {"r_msrvc_tokn_deny_accs", {"R_TOKN_MAIN r_msrvc_tokn_deny_accs", 0 }},
        {"r_msrvc_da_user_group", {"R_USER_GROUP r_msrvc_da_user_group", 0 }},
        {"r_msrvc_da_user_main", {"R_USER_MAIN r_msrvc_da_user_main", 0 }},
        {"r_msrvc_tokn_audit", {"R_TOKN_MAIN r_msrvc_tokn_audit", 0 }},
        {"r_msrvc_au_user_group", {"R_USER_GROUP r_msrvc_au_user_group", 0 }},
        {"r_msrvc_au_user_main", {"R_USER_MAIN r_msrvc_au_user_main", 0 }},

        {"R_TICKET_MAIN", {"R_TICKET_MAIN", 0 }},
        {"R_TICKET_ALLOWED_HOSTS", {"R_TICKET_ALLOWED_HOSTS", 0 }},
        {"R_TICKET_ALLOWED_USERS", {"R_TICKET_ALLOWED_USERS", 0 }},
        {"R_TICKET_ALLOWED_GROUPS", {"R_TICKET_ALLOWED_GROUPS", 0 }},
        {"r_ticket_coll_main", {"R_COLL_MAIN r_ticket_coll_main", 1 }},
        {"r_ticket_user_main", {"R_USER_MAIN r_ticket_user_main", 1 }},
        {"r_ticket_data_coll_main", {"R_COLL_MAIN r_ticket_data_coll_main", 1 }}
    }; // table alias cycler map

    /* Map the #define values to tables and columns */

    const std::map<std::string, std::tuple<std::string, std::string>> column_table_alias_map{
        {"ZONE_ID", {"R_ZONE_MAIN", "zone_id" }},
        {"ZONE_NAME", {"R_ZONE_MAIN", "zone_name" }},
        {"ZONE_TYPE", {"R_ZONE_MAIN", "zone_type_name" }},
        {"ZONE_CONNECTION", {"R_ZONE_MAIN", "zone_conn_string" }},
        {"ZONE_COMMENT", {"R_ZONE_MAIN", "r_comment" }},
        {"ZONE_CREATE_TIME", {"R_ZONE_MAIN", "create_ts" }},
        {"ZONE_MODIFY_TIME", {"R_ZONE_MAIN", "modify_ts" }},

        {"USER_ID", {"R_USER_MAIN", "user_id" }},
        {"USER_NAME", {"R_USER_MAIN", "user_name" }},
        {"USER_TYPE", {"R_USER_MAIN", "user_type_name" }},
        {"USER_ZONE", {"R_USER_MAIN", "zone_name" }},
        {"USER_INFO", {"R_USER_MAIN", "user_info" }},
        {"USER_COMMENT", {"R_USER_MAIN", "r_comment" }},
        {"USER_CREATE_TIME", {"R_USER_MAIN", "create_ts" }},
        {"USER_MODIFY_TIME", {"R_USER_MAIN", "modify_ts" }},

        {"USER_AUTH_ID", {"R_USER_AUTH", "user_id" }},
        {"USER_DN", {"R_USER_AUTH", "user_auth_name" }},

        {"USER_DN_INVALID", {"R_USER_MAIN", "r_comment" }}, /* compatibility */

        {"RESC_ID", {"R_RESC_MAIN", "resc_id" }},
        {"RESC_NAME", {"R_RESC_MAIN", "resc_name" }},
        {"ZONE_NAME", {"R_RESC_MAIN", "zone_name" }},
        {"TYPE_NAME", {"R_RESC_MAIN", "resc_type_name" }},
        {"CLASS_NAME", {"R_RESC_MAIN", "resc_class_name" }},
        {"LOC", {"R_RESC_MAIN", "resc_net" }},
        {"VAULT_PATH", {"R_RESC_MAIN", "resc_def_path " }},
        {"FREE_SPACE", {"R_RESC_MAIN", "free_space" }},
        {"FREE_SPACE_TIME", {"R_RESC_MAIN", "free_space_ts" }},
        {"RESC_INFO", {"R_RESC_MAIN", "resc_info" }},
        {"RESC_COMMENT", {"R_RESC_MAIN", "r_comment" }},
        {"RESC_STATUS", {"R_RESC_MAIN", "resc_status" }},
        {"CREATE_TIME", {"R_RESC_MAIN", "create_ts" }},
        {"RESC_MODIFY_TIME", {"R_RESC_MAIN", "modify_ts " }},
        {"RESC_CHILDREN", {"R_RESC_MAIN", "resc_children " }},
        {"RESC_CONTEXT", {"R_RESC_MAIN", "resc_context " }},
        {"RESC_PARENT", {"R_RESC_MAIN", "resc_parent " }},
        {"RESC_PARENT_CONTEXT", {"R_RESC_MAIN", "resc_parent_context" }},
        {"DATA_ID", {"R_DATA_MAIN", "data_id" }},
        {"COLL_ID", {"R_DATA_MAIN", "coll_id" }},
        {"DATA_NAME", {"R_DATA_MAIN", "data_name" }},
        {"DATA_REPL_NUM", {"R_DATA_MAIN", "data_repl_num" }},
        {"DATA_VERSION", {"R_DATA_MAIN", "data_version" }},
        {"DATA_TYPE_NAME", {"R_DATA_MAIN", "data_type_name" }},
        {"DATA_SIZE", {"R_DATA_MAIN", "data_size" }},
        {"DATA_PATH", {"R_DATA_MAIN", "data_path" }},
        {"OWNER_NAME", {"R_DATA_MAIN", "data_owner_name" }},
        {"OWNER_ZONE", {"R_DATA_MAIN", "data_owner_zone" }},
        {"DATA_REPL_STATUS", {"R_DATA_MAIN", "data_is_dirty" }},
        {"DATA_STATUS", {"R_DATA_MAIN", "data_status" }},
        {"DATA_CHECKSUM", {"R_DATA_MAIN", "data_checksum" }},
        {"EXPIRY", {"R_DATA_MAIN", "data_expiry_ts" }},
        {"MAP_ID", {"R_DATA_MAIN", "data_map_id" }},
        {"COMMENTS", {"R_DATA_MAIN", "r_comment" }},
        {"CREATE_TIME", {"R_DATA_MAIN", "create_ts" }},
        {"DATA_MODIFY_TIME", {"R_DATA_MAIN", "modify_ts" }},
        {"DATA_MODE", {"R_DATA_MAIN", "data_mode" }},

        {"DATA_RESC_ID", {"R_DATA_MAIN", "resc_id" }},

        {"DATA_ACCESS_TYPE", {"r_data_access", "access_type_id" }},
        {"DATA_ACCESS_NAME", {"r_data_tokn_accs", "token_name" }},
        {"DATA_TOKEN_NAMESPACE", {"r_data_tokn_accs", "token_namespace" }},
        {"DATA_ACCESS_USER_ID", {"r_data_access", "user_id" }},
        {"DATA_ACCESS_DATA_ID", {"r_data_access", "object_id" }},

        {"COLL_ACCESS_TYPE", {"r_coll_access", "access_type_id" }},
        {"COLL_ACCESS_NAME", {"r_coll_tokn_accs", "token_name" }},
        {"COLL_TOKEN_NAMESPACE", {"r_coll_tokn_accs", "token_namespace" }},
        {"COLL_ACCESS_USER_ID", {"r_coll_access", "user_id" }},
        {"COLL_ACCESS_COLL_ID", {"r_coll_access", "object_id" }},

        {"RESC_ACCESS_TYPE", {"r_resc_access", "access_type_id" }},
        {"RESC_ACCESS_NAME", {"r_resc_tokn_accs", "token_name" }},
        {"RESC_TOKEN_NAMESPACE", {"r_resc_tokn_accs", "token_namespace" }},
        {"RESC_ACCESS_USER_ID", {"r_resc_access", "user_id" }},
        {"RESC_ACCESS_RESC_ID", {"r_resc_access", "object_id" }},

        {"COLL_ID", {"R_COLL_MAIN", "coll_id" }},
        {"COLL_NAME", {"R_COLL_MAIN", "coll_name" }},
        {"COLL_PARENT_NAME", {"R_COLL_MAIN", "parent_coll_name" }},
        {"COLL_OWNER_NAME", {"R_COLL_MAIN", "coll_owner_name" }},
        {"COLL_OWNER_ZONE", {"R_COLL_MAIN", "coll_owner_zone" }},
        {"COLL_MAP_ID", {"R_COLL_MAIN", "coll_map_id" }},
        {"COLL_INHERITANCE", {"R_COLL_MAIN", "coll_inheritance" }},
        {"COLL_COMMENTS", {"R_COLL_MAIN", "r_comment" }},
        {"COLL_CREATE_TIME", {"R_COLL_MAIN", "create_ts" }},
        {"COLL_MODIFY_TIME", {"R_COLL_MAIN", "modify_ts" }},
        {"COLL_TYPE", {"R_COLL_MAIN", "coll_type" }},
        {"COLL_INFO1", {"R_COLL_MAIN", "coll_info1" }},
        {"COLL_INFO2", {"R_COLL_MAIN", "coll_info2" }},

        {"META_DATA_ATTR_NAME",  {"r_data_meta_main", "meta_attr_name" }},
        {"META_DATA_ATTR_VALUE", {"r_data_meta_main", "meta_attr_value" }},
        {"META_DATA_ATTR_UNITS", {"r_data_meta_main", "meta_attr_unit" }},
        {"META_DATA_ATTR_ID", {"r_data_meta_main", "meta_id" }},
        {"META_DATA_CREATE_TIME", {"r_data_meta_main", "create_ts" }},
        {"META_DATA_MODIFY_TIME", {"r_data_meta_main", "modify_ts" }},

        {"META_COLL_ATTR_NAME", {"r_coll_meta_main", "meta_attr_name" }},
        {"META_COLL_ATTR_VALUE", {"r_coll_meta_main", "meta_attr_value" }},
        {"META_COLL_ATTR_UNITS", {"r_coll_meta_main", "meta_attr_unit" }},
        {"META_COLL_ATTR_ID", {"r_coll_meta_main", "meta_id" }},
        {"META_COLL_CREATE_TIME", {"r_coll_meta_main", "create_ts" }},
        {"META_COLL_MODIFY_TIME", {"r_coll_meta_main", "modify_ts" }},

        {"META_NAMESPACE_COLL", {"r_coll_meta_main", "meta_namespace" }},
        {"META_NAMESPACE_DATA", {"r_data_meta_main", "meta_namespace" }},
        {"META_NAMESPACE_RESC", {"r_resc_meta_main", "meta_namespace" }},
        {"META_NAMESPACE_RESC_GROUP", {"r_resc_grp_meta_main", "meta_namespace" }},
        {"META_NAMESPACE_USER", {"r_user_meta_main", "meta_namespace" }},
        {"META_NAMESPACE_RULE", {"r_rule_meta_main", "meta_namespace" }},
        {"META_NAMESPACE_MSRVC", {"r_msrvc_meta_main", "meta_namespace" }},
        {"META_NAMESPACE_MET2", {"r_met2_meta_main", "meta_namespace" }},


        {"META_RESC_ATTR_NAME", {"r_resc_meta_main", "meta_attr_name" }},
        {"META_RESC_ATTR_VALUE", {"r_resc_meta_main", "meta_attr_value" }},
        {"META_RESC_ATTR_UNITS", {"r_resc_meta_main", "meta_attr_unit" }},
        {"META_RESC_ATTR_ID", {"r_resc_meta_main", "meta_id" }},
        {"META_RESC_CREATE_TIME", {"r_resc_meta_main", "create_ts" }},
        {"META_RESC_MODIFY_TIME", {"r_resc_meta_main", "modify_ts" }},

        {"META_RESC_GROUP_ATTR_NAME", {"r_resc_grp_meta_main", "meta_attr_name" }},
        {"META_RESC_GROUP_ATTR_VALUE", {"r_resc_grp_meta_main", "meta_attr_value" }},
        {"META_RESC_GROUP_ATTR_UNITS", {"r_resc_grp_meta_main", "meta_attr_unit" }},
        {"META_RESC_GROUP_ATTR_ID", {"r_resc_grp_meta_main", "meta_id" }},
        {"META_RESC_GROUP_CREATE_TIME", {"r_resc_grp_meta_main", "create_ts" }},
        {"META_RESC_GROUP_MODIFY_TIME", {"r_resc_grp_meta_main", "modify_ts" }},

        {"META_USER_ATTR_NAME", {"r_user_meta_main", "meta_attr_name" }},
        {"META_USER_ATTR_VALUE", {"r_user_meta_main", "meta_attr_value" }},
        {"META_USER_ATTR_UNITS", {"r_user_meta_main", "meta_attr_unit" }},
        {"META_USER_ATTR_ID", {"r_user_meta_main", "meta_id" }},
        {"META_USER_CREATE_TIME", {"r_user_meta_main", "create_ts" }},
        {"META_USER_MODIFY_TIME", {"r_user_meta_main", "modify_ts" }},

        {"META_RULE_ATTR_NAME", {"r_rule_meta_main", "meta_attr_name" }},
        {"META_RULE_ATTR_VALUE", {"r_rule_meta_main", "meta_attr_value" }},
        {"META_RULE_ATTR_UNITS", {"r_rule_meta_main", "meta_attr_unit" }},
        {"META_RULE_ATTR_ID", {"r_rule_meta_main", "meta_id" }},
        {"META_RULE_CREATE_TIME", {"r_rule_meta_main", "create_ts" }},
        {"META_RULE_MODIFY_TIME", {"r_rule_meta_main", "modify_ts" }},

        {"META_MSRVC_ATTR_NAME", {"r_msrvc_meta_main", "meta_attr_name" }},
        {"META_MSRVC_ATTR_VALUE", {"r_msrvc_meta_main", "meta_attr_value" }},
        {"META_MSRVC_ATTR_UNITS", {"r_msrvc_meta_main", "meta_attr_unit" }},
        {"META_MSRVC_ATTR_ID", {"r_msrvc_meta_main", "meta_id" }},
        {"META_MSRVC_CREATE_TIME", {"r_msrvc_meta_main", "create_ts" }},
        {"META_MSRVC_MODIFY_TIME", {"r_msrvc_meta_main", "modify_ts" }},

        {"META_MET2_ATTR_NAME", {"r_met2_meta_main", "meta_attr_name" }},
        {"META_MET2_ATTR_VALUE", {"r_met2_meta_main", "meta_attr_value" }},
        {"META_MET2_ATTR_UNITS", {"r_met2_meta_main", "meta_attr_unit" }},
        {"META_MET2_ATTR_ID", {"r_met2_meta_main", "meta_id" }},
        {"META_MET2_CREATE_TIME", {"r_met2_meta_main", "create_ts" }},
        {"META_MET2_MODIFY_TIME", {"r_met2_meta_main", "modify_ts" }},

        {"USER_GROUP_ID", {"R_USER_GROUP",  "group_user_id" }},
        {"USER_GROUP_NAME", {"r_group_main", "user_name" }},

        {"RULE_EXEC_ID", {"R_RULE_EXEC", "rule_exec_id" }},
        {"RULE_EXEC_NAME", {"R_RULE_EXEC", "rule_name" }},
        {"RULE_EXEC_REI_FILE_PATH", {"R_RULE_EXEC", "rei_file_path" }},
        {"RULE_EXEC_USER_NAME", {"R_RULE_EXEC", "user_name" }},
        {"RULE_EXEC_ADDRESS", {"R_RULE_EXEC", "exe_address" }},
        {"RULE_EXEC_TIME", {"R_RULE_EXEC", "exe_time" }},
        {"RULE_EXEC_FREQUENCY", {"R_RULE_EXEC", "exe_frequency" }},
        {"RULE_EXEC_PRIORITY", {"R_RULE_EXEC", "priority" }},
        {"RULE_EXEC_ESTIMATED_EXE_TIME", {"R_RULE_EXEC", "estimated_exe_time" }},
        {"RULE_EXEC_NOTIFICATION_ADDR", {"R_RULE_EXEC", "notification_addr" }},
        {"RULE_EXEC_LAST_EXE_TIME", {"R_RULE_EXEC", "last_exe_time" }},
        {"RULE_EXEC_STATUS", {"R_RULE_EXEC", "exe_status" }},

        {"TOKEN_NAMESPACE", {"R_TOKN_MAIN", "token_namespace" }},
        {"TOKEN_ID", {"R_TOKN_MAIN", "token_id" }},
        {"TOKEN_NAME", {"R_TOKN_MAIN", "token_name" }},
        {"TOKEN_VALUE", {"R_TOKN_MAIN", "token_value" }},
        {"TOKEN_VALUE2", {"R_TOKN_MAIN", "token_value2" }},
        {"TOKEN_VALUE3", {"R_TOKN_MAIN", "token_value3" }},
        {"TOKEN_COMMENT", {"R_TOKN_MAIN", "r_comment" }},

        {"AUDIT_OBJ_ID", {"R_OBJT_AUDIT", "object_id" }},
        {"AUDIT_USER_ID", {"R_OBJT_AUDIT", "user_id" }},
        {"AUDIT_ACTION_ID", {"R_OBJT_AUDIT", "action_id" }},
        {"AUDIT_COMMENT", {"R_OBJT_AUDIT", "r_comment" }},
        {"AUDIT_CREATE_TIME", {"R_OBJT_AUDIT", "create_ts" }},
        {"AUDIT_MODIFY_TIME", {"R_OBJT_AUDIT", "modify_ts" }},

        {"COLL_USER_NAME", {"r_coll_user_main", "user_name" }},
        {"COLL_USER_ZONE", {"r_coll_user_main", "zone_name" }},

        {"DATA_USER_NAME", {"r_data_user_main", "user_name" }},
        {"DATA_USER_ZONE", {"r_data_user_main", "zone_name" }},

        {"RESC_USER_NAME", {"r_resc_user_main", "user_name" }},
        {"RESC_USER_ZONE", {"r_resc_user_main", "zone_name" }},

        {"SL_HOST_NAME", {"R_SERVER_LOAD", "host_name" }},
        {"SL_RESC_NAME", {"R_SERVER_LOAD", "resc_name" }},
        {"SL_CPU_USED", {"R_SERVER_LOAD", "cpu_used" }},
        {"SL_MEM_USED", {"R_SERVER_LOAD", "mem_used" }},
        {"SL_SWAP_USED", {"R_SERVER_LOAD", "swap_used" }},
        {"SL_RUNQ_LOAD", {"R_SERVER_LOAD", "runq_load" }},
        {"SL_DISK_SPACE", {"R_SERVER_LOAD", "disk_space" }},
        {"SL_NET_INPUT", {"R_SERVER_LOAD", "net_input" }},
        {"SL_NET_OUTPUT", {"R_SERVER_LOAD", "net_output" }},
        {"SL_CREATE_TIME", {"R_SERVER_LOAD", "create_ts" }},

        {"SLD_RESC_NAME", {"R_SERVER_LOAD_DIGEST", "resc_name" }},
        {"SLD_LOAD_FACTOR", {"R_SERVER_LOAD_DIGEST", "load_factor" }},
        {"SLD_CREATE_TIME", {"R_SERVER_LOAD_DIGEST", "create_ts" }},

        {"RULE_ID", {"R_RULE_MAIN", "rule_id" }},
        {"RULE_VERSION", {"R_RULE_MAIN", "rule_version" }},
        {"RULE_BASE_NAME", {"R_RULE_MAIN", "rule_base_name" }},
        {"RULE_NAME", {"R_RULE_MAIN", "rule_name" }},
        {"RULE_EVENT", {"R_RULE_MAIN", "rule_event" }},
        {"RULE_CONDITION", {"R_RULE_MAIN", "rule_condition" }},
        {"RULE_BODY", {"R_RULE_MAIN", "rule_body" }},
        {"RULE_RECOVERY", {"R_RULE_MAIN", "rule_recovery" }},
        {"RULE_STATUS", {"R_RULE_MAIN", "rule_status" }},
        {"RULE_OWNER_NAME", {"R_RULE_MAIN", "rule_owner_name" }},
        {"RULE_OWNER_ZONE", {"R_RULE_MAIN", "rule_owner_zone" }},
        {"RULE_DESCR_1", {"R_RULE_MAIN", "rule_descr_1" }},
        {"RULE_DESCR_2", {"R_RULE_MAIN", "rule_descr_2" }},
        {"RULE_INPUT_PARAMS", {"R_RULE_MAIN", "input_params" }},
        {"RULE_OUTPUT_PARAMS", {"R_RULE_MAIN", "output_params" }},
        {"RULE_DOLLAR_VARS", {"R_RULE_MAIN", "dollar_vars" }},
        {"RULE_ICAT_ELEMENTS", {"R_RULE_MAIN", "icat_elements" }},
        {"RULE_SIDEEFFECTS", {"R_RULE_MAIN", "sideeffects" }},
        {"RULE_COMMENT", {"R_RULE_MAIN", "r_comment" }},
        {"RULE_CREATE_TIME", {"R_RULE_MAIN", "create_ts" }},
        {"RULE_MODIFY_TIME", {"R_RULE_MAIN", "modify_ts" }},

        {"RULE_BASE_MAP_VERSION", {"R_RULE_BASE_MAP", "map_version" }},
        {"RULE_BASE_MAP_PRIORITY", {"R_RULE_BASE_MAP", "map_priority" }},
        {"RULE_BASE_MAP_BASE_NAME", {"R_RULE_BASE_MAP", "map_base_name" }},
        {"RULE_BASE_MAP_OWNER_NAME", {"R_RULE_BASE_MAP", "map_owner_name" }},
        {"RULE_BASE_MAP_OWNER_ZONE", {"R_RULE_BASE_MAP", "map_owner_zone" }},
        {"RULE_BASE_MAP_COMMENT", {"R_RULE_BASE_MAP", "r_comment" }},
        {"RULE_BASE_MAP_CREATE_TIME", {"R_RULE_BASE_MAP", "create_ts" }},
        {"RULE_BASE_MAP_MODIFY_TIME", {"R_RULE_BASE_MAP", "modify_ts" }},

        {"DVM_ID", {"R_RULE_DVM", "dvm_id" }},
        {"DVM_VERSION", {"R_RULE_DVM", "dvm_version" }},
        {"DVM_BASE_NAME", {"R_RULE_DVM", "dvm_base_name" }},
        {"DVM_EXT_VAR_NAME", {"R_RULE_DVM", "dvm_ext_var_name" }},
        {"DVM_CONDITION", {"R_RULE_DVM", "dvm_condition" }},
        {"DVM_INT_MAP_PATH", {"R_RULE_DVM", "dvm_int_map_path" }},
        {"DVM_STATUS", {"R_RULE_DVM", "dvm_status" }},
        {"DVM_OWNER_NAME", {"R_RULE_DVM", "dvm_owner_name" }},
        {"DVM_OWNER_ZONE", {"R_RULE_DVM", "dvm_owner_zone" }},
        {"DVM_COMMENT", {"R_RULE_DVM", "r_comment" }},
        {"DVM_CREATE_TIME", {"R_RULE_DVM", "create_ts" }},
        {"DVM_MODIFY_TIME", {"R_RULE_DVM", "modify_ts" }},

        {"DVM_BASE_MAP_VERSION", {"R_RULE_DVM_MAP", "map_dvm_version" }},
        {"DVM_BASE_MAP_BASE_NAME", {"R_RULE_DVM_MAP", "map_dvm_base_name" }},
        {"DVM_BASE_MAP_OWNER_NAME", {"R_RULE_DVM_MAP", "map_owner_name" }},
        {"DVM_BASE_MAP_OWNER_ZONE", {"R_RULE_DVM_MAP", "map_owner_zone" }},
        {"DVM_BASE_MAP_COMMENT", {"R_RULE_DVM_MAP", "r_comment" }},
        {"DVM_BASE_MAP_CREATE_TIME", {"R_RULE_DVM_MAP", "create_ts" }},
        {"DVM_BASE_MAP_MODIFY_TIME", {"R_RULE_DVM_MAP", "modify_ts" }},

        {"FNM_ID", {"R_RULE_FNM", "fnm_id" }},
        {"FNM_VERSION", {"R_RULE_FNM", "fnm_version" }},
        {"FNM_BASE_NAME", {"R_RULE_FNM", "fnm_base_name" }},
        {"FNM_EXT_FUNC_NAME", {"R_RULE_FNM", "fnm_ext_func_name" }},
        {"FNM_INT_FUNC_NAME", {"R_RULE_FNM", "fnm_int_func_name" }},
        {"FNM_STATUS", {"R_RULE_FNM", "fnm_status" }},
        {"FNM_OWNER_NAME", {"R_RULE_FNM", "fnm_owner_name" }},
        {"FNM_OWNER_ZONE", {"R_RULE_FNM", "fnm_owner_zone" }},
        {"FNM_COMMENT", {"R_RULE_FNM", "r_comment" }},
        {"FNM_CREATE_TIME", {"R_RULE_FNM", "create_ts" }},
        {"FNM_MODIFY_TIME", {"R_RULE_FNM", "modify_ts" }},

        {"FNM_BASE_MAP_VERSION", {"R_RULE_FNM_MAP", "map_fnm_version" }},
        {"FNM_BASE_MAP_BASE_NAME", {"R_RULE_FNM_MAP", "map_fnm_base_name" }},
        {"FNM_BASE_MAP_OWNER_NAME", {"R_RULE_FNM_MAP", "map_owner_name" }},
        {"FNM_BASE_MAP_OWNER_ZONE", {"R_RULE_FNM_MAP", "map_owner_zone" }},
        {"FNM_BASE_MAP_COMMENT", {"R_RULE_FNM_MAP", "r_comment" }},
        {"FNM_BASE_MAP_CREATE_TIME", {"R_RULE_FNM_MAP", "create_ts" }},
        {"FNM_BASE_MAP_MODIFY_TIME", {"R_RULE_FNM_MAP", "modify_ts" }},

        {"QUOTA_USER_ID", {"R_QUOTA_MAIN", "user_id" }},
        {"QUOTA_RESC_ID", {"R_QUOTA_MAIN", "resc_id" }},
        {"QUOTA_LIMIT", {"R_QUOTA_MAIN", "quota_limit" }},
        {"QUOTA_OVER", {"R_QUOTA_MAIN", "quota_over" }},
        {"QUOTA_MODIFY_TIME", {"R_QUOTA_MAIN", "modify_ts" }},

        {"QUOTA_USAGE_USER_ID", {"R_QUOTA_USAGE", "user_id" }},
        {"QUOTA_USAGE_RESC_ID", {"R_QUOTA_USAGE", "resc_id" }},
        {"QUOTA_USAGE", {"R_QUOTA_USAGE", "quota_usage" }},
        {"QUOTA_USAGE_MODIFY_TIME", {"R_QUOTA_USAGE", "modify_ts" }},

        {"QUOTA_USER_NAME", {"r_quota_user_main", "user_name" }},
        {"QUOTA_USER_TYPE", {"r_quota_user_group", "user_type_name" }},
        {"QUOTA_RESC_NAME", {"r_quota_resc_main", "resc_name" }},
        {"QUOTA_USER_ZONE", {"r_quota_user_main", "zone_name" }},

        {"MSRVC_ID", {"R_MICROSRVC_MAIN", "msrvc_id" }},
        {"MSRVC_MODULE_NAME", {"R_MICROSRVC_MAIN", "msrvc_module_name" }},
        {"MSRVC_NAME", {"R_MICROSRVC_MAIN", "msrvc_name" }},
        {"MSRVC_SIGNATURE", {"R_MICROSRVC_MAIN", "msrvc_signature" }},
        {"MSRVC_DOXYGEN", {"R_MICROSRVC_MAIN", "msrvc_doxygen" }},
        {"MSRVC_VARIATIONS", {"R_MICROSRVC_MAIN", "msrvc_variations" }},
        {"MSRVC_OWNER_NAME", {"R_MICROSRVC_MAIN", "msrvc_owner_name" }},
        {"MSRVC_OWNER_ZONE", {"R_MICROSRVC_MAIN", "msrvc_owner_zone" }},
        {"MSRVC_COMMENT", {"R_MICROSRVC_MAIN", "r_comment" }},
        {"MSRVC_CREATE_TIME", {"R_MICROSRVC_MAIN", "create_ts" }},
        {"MSRVC_MODIFY_TIME", {"R_MICROSRVC_MAIN", "modify_ts" }},

        {"MSRVC_VERSION", {"R_MICROSRVC_VER", "msrvc_version" }},
        {"MSRVC_HOST", {"R_MICROSRVC_VER", "msrvc_host" }},
        {"MSRVC_LOCATION", {"R_MICROSRVC_VER", "msrvc_location" }},
        {"MSRVC_LANGUAGE", {"R_MICROSRVC_VER", "msrvc_language" }},
        {"MSRVC_TYPE_NAME", {"R_MICROSRVC_VER", "msrvc_type_name" }},
        {"MSRVC_STATUS", {"R_MICROSRVC_VER", "msrvc_status" }},
        {"MSRVC_VER_OWNER_NAME", {"R_MICROSRVC_VER", "msrvc_owner_name" }},
        {"MSRVC_VER_OWNER_ZONE", {"R_MICROSRVC_VER", "msrvc_owner_zone" }},
        {"MSRVC_VER_COMMENT", {"R_MICROSRVC_VER", "r_comment" }},
        {"MSRVC_VER_CREATE_TIME", {"R_MICROSRVC_VER", "create_ts" }},
        {"MSRVC_VER_MODIFY_TIME", {"R_MICROSRVC_VER", "modify_ts" }},

        {"META_ACCESS_TYPE", {"r_meta_access", "access_type_id" }},
        {"META_ACCESS_NAME", {"r_meta_tokn_accs", "token_name" }},
        {"META_TOKEN_NAMESPACE", {"r_meta_tokn_accs", "token_namespace" }},
        {"META_ACCESS_USER_ID", {"r_meta_access", "user_id" }},
        {"META_ACCESS_META_ID", {"r_meta_access", "object_id" }},

        {"RESC_ACCESS_TYPE", {"r_resc_access", "access_type_id" }},
        {"RESC_ACCESS_NAME", {"r_resc_tokn_accs", "token_name" }},
        {"RESC_TOKEN_NAMESPACE", {"r_resc_tokn_accs", "token_namespace" }},
        {"RESC_ACCESS_USER_ID", {"r_resc_access", "user_id" }},
        {"RESC_ACCESS_RESC_ID", {"r_resc_access", "object_id" }},

        {"RULE_ACCESS_TYPE", {"r_rule_access", "access_type_id" }},
        {"RULE_ACCESS_NAME", {"r_rule_tokn_accs", "token_name" }},
        {"RULE_TOKEN_NAMESPACE", {"r_rule_tokn_accs", "token_namespace" }},
        {"RULE_ACCESS_USER_ID", {"r_rule_access", "user_id" }},
        {"RULE_ACCESS_RULE_ID", {"r_rule_access", "object_id" }},

        {"MSRVC_ACCESS_TYPE", {"r_msrvc_access", "access_type_id" }},
        {"MSRVC_ACCESS_NAME", {"r_msrvc_tokn_accs", "token_name" }},
        {"MSRVC_TOKEN_NAMESPACE", {"r_msrvc_tokn_accs", "token_namespace" }},
        {"MSRVC_ACCESS_USER_ID", {"r_msrvc_access", "user_id" }},
        {"MSRVC_ACCESS_MSRVC_ID", {"r_msrvc_access", "object_id" }},

        {"TICKET_ID", {"R_TICKET_MAIN", "ticket_id" }},
        {"TICKET_STRING", {"R_TICKET_MAIN", "ticket_string" }},
        {"TICKET_TYPE", {"R_TICKET_MAIN", "ticket_type" }},
        {"TICKET_USER_ID", {"R_TICKET_MAIN", "user_id" }},
        {"TICKET_OBJECT_ID", {"R_TICKET_MAIN", "object_id" }},
        {"TICKET_OBJECT_TYPE", {"R_TICKET_MAIN", "object_type" }},
        {"TICKET_USES_LIMIT", {"R_TICKET_MAIN", "uses_limit" }},
        {"TICKET_USES_COUNT", {"R_TICKET_MAIN", "uses_count" }},
        {"TICKET_WRITE_FILE_LIMIT", {"R_TICKET_MAIN", "write_file_limit" }},
        {"TICKET_WRITE_FILE_COUNT", {"R_TICKET_MAIN", "write_file_count" }},
        {"TICKET_WRITE_BYTE_LIMIT", {"R_TICKET_MAIN", "write_byte_limit" }},
        {"TICKET_WRITE_BYTE_COUNT", {"R_TICKET_MAIN", "write_byte_count" }},
        {"TICKET_EXPIRY_TS", {"R_TICKET_MAIN", "ticket_expiry_ts" }},
        {"TICKET_CREATE_TIME", {"R_TICKET_MAIN", "create_time" }},
        {"TICKET_MODIFY_TIME", {"R_TICKET_MAIN", "modify_time" }},

        {"TICKET_ALLOWED_HOST", {"R_TICKET_ALLOWED_HOSTS", "host" }},
        {"TICKET_ALLOWED_HOST_TICKET_ID", {"R_TICKET_ALLOWED_HOSTS", "ticket_id" }},
        {"TICKET_ALLOWED_USER_NAME", {"R_TICKET_ALLOWED_USERS", "user_name" }},
        {"TICKET_ALLOWED_USER_TICKET_ID", {"R_TICKET_ALLOWED_USERS", "ticket_id" }},
        {"TICKET_ALLOWED_GROUP_NAME", {"R_TICKET_ALLOWED_GROUPS", "group_name" }},
        {"TICKET_ALLOWED_GROUP_TICKET_ID", {"R_TICKET_ALLOWED_GROUPS", "ticket_id" }},

        {"TICKET_DATA_NAME", {"R_DATA_MAIN", "data_name" }},
        {"TICKET_COLL_NAME", {"r_ticket_coll_main", "coll_name" }},
        {"TICKET_OWNER_NAME", {"r_ticket_user_main", "user_name" }},
        {"TICKET_OWNER_ZONE", {"r_ticket_user_main", "zone_name" }},
        {"TICKET_DATA_COLL_NAME", {"r_ticket_data_coll_main", "coll_name" }}
    }; // column_table_alias_map

    /* Define the Foreign Key links between tables */

    const std::vector<std::tuple<std::string, std::string, std::string>> foreign_key_link_map{
        {"R_COLL_MAIN", "R_DATA_MAIN", "R_COLL_MAIN.coll_id = R_DATA_MAIN.coll_id" },
        {"R_RESC_GROUP", "R_RESC_MAIN", "R_RESC_GROUP.resc_id = R_RESC_MAIN.resc_id" },
        {"R_RESC_MAIN", "r_resc_metamap", "R_RESC_MAIN.resc_id = r_resc_metamap.object_id" },
        {"R_RESC_MAIN", "R_DATA_MAIN", "R_RESC_MAIN.resc_id = R_DATA_MAIN.resc_id" },
        {"R_RESC_GROUP", "r_resc_grp_metamap", "R_RESC_GROUP.resc_group_id = r_resc_grp_metamap.object_id" },
        {"R_COLL_MAIN", "r_coll_metamap", "R_COLL_MAIN.coll_id = r_coll_metamap.object_id" },

        {"R_DATA_MAIN", "r_data_metamap", "R_DATA_MAIN.data_id = r_data_metamap.object_id" },

        {"R_RULE_MAIN", "r_rule_metamap", "R_RULE_MAIN.rule_id = r_rule_metamap.object_id" },
        {"R_USER_MAIN", "r_user_metamap", "R_USER_MAIN.user_id = r_user_metamap.object_id" },
        {"r_met2_main", "r_met2_metamap", "r_met2_main.meta_id = r_met2_metamap.object_id" },
        {"R_RESC_MAIN", "r_resc_access", "R_RESC_MAIN.resc_id = r_resc_access.object_id" },
        {"R_COLL_MAIN", "r_coll_access", "R_COLL_MAIN.coll_id = r_coll_access.object_id" },
        {"R_DATA_MAIN", "r_data_access", "R_DATA_MAIN.data_id = r_data_access.object_id" },
        {"R_RULE_MAIN", "r_rule_access", "R_RULE_MAIN.rule_id = r_rule_access.object_id" },
        {"r_met2_main", "r_met2_access", "r_met2_main.meta_id = r_met2_access.object_id" },
        {"R_RESC_MAIN", "r_resc_deny_access", "R_RESC_MAIN.resc_id = r_resc_deny_access.object_id" },
        {"R_COLL_MAIN", "r_coll_deny_access", "R_COLL_MAIN.coll_id = r_coll_deny_access.object_id" },
        {"R_DATA_MAIN", "r_data_deny_access", "R_DATA_MAIN.data_id = r_data_deny_access.object_id" },
        {"R_RULE_MAIN", "r_rule_deny_access", "R_RULE_MAIN.rule_id = r_rule_deny_access.object_id" },
        {"r_met2_main", "r_met2_deny_access", "r_met2_main.meta_id = r_met2_deny_access.object_id" },
        {"R_RESC_MAIN", "r_resc_audit", "R_RESC_MAIN.resc_id = r_resc_audit.object_id" },
        {"R_COLL_MAIN", "r_coll_audit", "R_COLL_MAIN.coll_id = r_coll_audit.object_id" },
        {"R_DATA_MAIN", "r_data_audit", "R_DATA_MAIN.data_id = r_data_audit.object_id" },
        {"R_RULE_MAIN", "r_rule_audit", "R_RULE_MAIN.rule_id = r_rule_audit.object_id" },
        {"r_met2_main", "r_met2_audit", "r_met2_main.meta_id = r_met2_audit.object_id.meta_id" },
        {"r_resc_metamap", "r_resc_meta_main",  "r_resc_metamap.meta_id = r_resc_meta_main.meta_id" },
        {"r_resc_grp_metamap", "r_resc_grp_meta_main",  "r_resc_grp_metamap.meta_id = r_resc_grp_meta_main.meta_id" },
        {"r_coll_metamap", "r_coll_meta_main",  "r_coll_metamap.meta_id = r_coll_meta_main.meta_id" },

        {"r_data_metamap", "r_data_meta_main",  "r_data_metamap.meta_id = r_data_meta_main.meta_id" },

        {"r_rule_metamap", "r_rule_meta_main",  "r_rule_metamap.meta_id = r_rule_meta_main.meta_id" },
        {"r_user_metamap", "r_user_meta_main",  "r_user_metamap.meta_id = r_user_meta_main.meta_id" },
        {"r_met2_metamap", "r_met2_meta_main",  "r_met2_metamap.object_id = r_met2_meta_main.meta_id" },
        {"r_resc_access", "r_resc_tokn_accs",  "r_resc_access.access_type_id = r_resc_tokn_accs.token_id" },
        {"r_resc_access", "r_resc_user_group", "r_resc_access.user_id = r_resc_user_group.group_user_id" },
        {"r_coll_access", "r_coll_tokn_accs",  "r_coll_access.access_type_id = r_coll_tokn_accs.token_id" },
        {"r_coll_access", "r_coll_user_group", "r_coll_access.user_id = r_coll_user_group.group_user_id" },
        {"r_data_access", "r_data_tokn_accs",  "r_data_access.access_type_id = r_data_tokn_accs.token_id" },
        {"r_data_access", "r_data_user_group", "r_data_access.user_id = r_data_user_group.group_user_id" },
        {"r_rule_access", "r_rule_tokn_accs",  "r_rule_access.access_typ_id = r_rule_tokn_accs.token_id" },
        {"r_rule_access", "r_rule_user_group", "r_rule_access.user_id = r_rule_user_group.group_user_id" },
        {"r_met2_access", "r_met2_tokn_accs",  "r_met2_access.access_typ_id = r_met2_tokn_accs.token_id" },
        {"r_met2_access", "r_met2_user_group", "r_met2_access.user_id = r_met2_user_group.group_user_id" },
        {"r_resc_deny_access", "r_resc_tokn_deny_accs", "r_resc_deny_access.access_typ_id = r_resc_tokn_deny_accs.token_id" },
        {"r_resc_deny_access", "r_resc_da_user_group",     "r_resc_deny_access.user_id = r_resc_da_user_group.group_user_id" },
        {"r_coll_deny_access", "r_coll_tokn_deny_accs", "r_coll_deny_access.access_typ_id = r_coll_tokn_deny_accs.token_id" },
        {"r_coll_deny_access", "r_coll_da_user_group",     "r_coll_deny_access.user_id = r_coll_da_user_group.group_user_id" },
        {"r_data_deny_access", "r_data_tokn_deny_accs", "r_data_deny_access.access_typ_id = r_data_tokn_deny_accs.token_id" },
        {"r_data_deny_access", "r_data_da_user_group",     "r_data_deny_access.user_id = r_data_da_user_group.group_user_id" },
        {"r_rule_deny_access", "r_rule_tokn_deny_accs", "r_rule_deny_access.access_typ_id = r_rule_tokn_deny_accs.token_id" },
        {"r_rule_deny_access", "r_rule_da_user_group",     "r_rule_deny_access.user_id = r_rule_da_user_group.group_user_id" },
        {"r_met2_deny_access", "r_met2_tokn_deny_accs", "r_met2_deny_access.access_typ_id = r_met2_tokn_deny_accs.token_id" },
        {"r_met2_deny_access", "r_met2_da_user_group",     "r_met2_deny_access.user_id = r_met2_da_user_group.group_user_id" },
        {"r_resc_audit", "r_resc_tokn_audit", "r_resc_audit.action_id = r_resc_tokn_audit.token_id" },
        {"r_resc_audit", "r_resc_au_user_group", "r_resc_audit.user_id = r_resc_au_user_group.group_user_id" },
        {"r_coll_audit", "r_coll_tokn_audit", "r_coll_audit.action_id = r_coll_tokn_audit.token_id" },
        {"r_coll_audit", "r_coll_au_user_group", "r_coll_audit.user_id = r_coll_au_user_group.group_user_id" },
        {"r_data_audit", "r_data_tokn_audit", "r_data_audit.action_id = r_data_tokn_audit.token_id" },
        {"r_data_audit", "r_data_au_user_group", "r_data_audit.user_id = r_data_au_user_group.group_user_id" },
        {"r_rule_audit", "r_rule_tokn_audit", "r_rule_audit.action_id = r_rule_tokn_audit.token_id" },
        {"r_rule_audit", "r_rule_au_user_group", "r_rule_audit.user_id = r_rule_au_user_group.group_user_id" },
        {"r_met2_audit", "r_met2_tokn_audit", "r_met2_audit.action_id = r_met2_tokn_audit.token_id" },
        {"r_met2_audit", "r_met2_au_user_group", "r_met2_audit.user_id = r_met2_au_user_group.group_user_id" },
        {"r_resc_user_group", "r_resc_user_main", "r_resc_user_group.user_id = r_resc_user_main.user_id" },
        {"r_coll_user_group", "r_coll_user_main", "r_coll_user_group.user_id = r_coll_user_main.user_id" },
        {"r_data_user_group", "r_data_user_main", "r_data_user_group.user_id = r_data_user_main.user_id" },
        {"r_rule_user_group", "r_rule_user_main", "r_rule_user_group.user_id = r_rule_user_main.user_id" },
        {"r_met2_user_group", "r_met2_user_main", "r_met2_user_group.user_id = r_met2_user_main.user_id" },
        {"r_resc_da_user_group", "r_resc_da_user_main", "r_resc_da_user_group.user_id = r_resc_da_user_main.user_id" },
        {"r_coll_da_user_group", "r_coll_da_user_main", "r_coll_da_user_group.user_id = r_coll_da_user_main.user_id" },
        {"r_data_da_user_group", "r_data_da_user_main", "r_data_da_user_group.user_id = r_data_da_user_main.user_id" },
        {"r_rule_da_user_group", "r_rule_da_user_main", "r_rule_da_user_group.user_id = r_rule_da_user_main.user_id" },
        {"r_met2_da_user_group", "r_met2_da_user_main", "r_met2_da_user_group.user_id = r_met2_da_user_main.user_id" },
        {"r_resc_au_user_group", "r_resc_au_user_main", "r_resc_au_user_group.user_id = r_resc_au_user_main.user_id" },
        {"r_coll_au_user_group", "r_coll_au_user_main", "r_coll_au_user_group.user_id = r_coll_au_user_main.user_id" },
        {"r_data_au_user_group", "r_data_au_user_main", "r_data_au_user_group.user_id = r_data_au_user_main.user_id" },
        {"r_rule_au_user_group", "r_rule_au_user_main", "r_rule_au_user_group.user_id = r_rule_au_user_main.user_id" },
        {"r_met2_au_user_group", "r_met2_au_user_main", "r_met2_au_user_group.user_id = r_met2_au_user_main.user_id" },
        {"R_USER_MAIN", "R_USER_PASSWORD", "R_USER_MAIN.user_id = R_USER_PASSWORD.user_id" },
        {"R_USER_MAIN", "R_USER_AUTH", "R_USER_MAIN.user_id = R_USER_AUTH.user_id" },
        {"R_USER_MAIN", "R_USER_SESSION_KEY", "R_USER_MAIN.user_id = R_USER_SESSION_KEY.user_id" },
        {"R_USER_MAIN", "r_data_access", "R_USER_MAIN.user_id = r_data_access.user_id" },
        {"R_USER_MAIN", "R_USER_GROUP", "R_USER_MAIN.user_id = R_USER_GROUP.user_id" },
        {"R_USER_GROUP", "r_group_main", "R_USER_GROUP.group_user_id = r_group_main.user_id" },
        {"R_USER_MAIN", "R_OBJT_AUDIT", "R_USER_MAIN.user_id = R_OBJT_AUDIT.user_id" },

        {"R_QUOTA_MAIN", "r_quota_user_main", "R_QUOTA_MAIN.user_id = r_quota_user_main.user_id" },
        {"R_QUOTA_MAIN", "r_quota_resc_main", "R_QUOTA_MAIN.resc_id = r_quota_resc_main.resc_id" },
        {"R_QUOTA_MAIN", "r_quota_user_group", "R_QUOTA_MAIN.user_id = r_quota_user_group.user_id" },
        {"R_QUOTA_USAGE", "r_quota_user_main", "R_QUOTA_USAGE.user_id = r_quota_user_main.user_id" },
        {"R_QUOTA_USAGE", "r_quota_resc_main", "R_QUOTA_USAGE.resc_id = r_quota_resc_main.resc_id" },
        {"R_QUOTA_USAGE", "r_quota_user_group", "R_QUOTA_USAGE.user_id = r_quota_user_group.user_id" },
        {"R_RULE_BASE_MAP", "R_RULE_MAIN", "R_RULE_BASE_MAP.rule_id = R_RULE_MAIN.rule_id" },
        {"R_RULE_DVM_MAP", "R_RULE_DVM", "R_RULE_DVM_MAP.dvm_id = R_RULE_DVM.dvm_id" },
        {"R_RULE_FNM_MAP", "R_RULE_FNM", "R_RULE_FNM_MAP.fnm_id = R_RULE_FNM.fnm_id" },

        {"R_MICROSRVC_MAIN", "R_MICROSRVC_VER", "R_MICROSRVC_MAIN.msrvc_id = R_MICROSRVC_VER.msrvc_id" },
        {"R_MICROSRVC_MAIN", "r_msrvc_metamap", "R_MICROSRVC_MAIN.msrvc_id = r_msrvc_metamap.object_id" },
        {"r_msrvc_metamap", "r_msrvc_meta_main",  "r_msrvc_metamap.meta_id = r_msrvc_meta_main.meta_id" },
        {"R_MICROSRVC_MAIN", "r_msrvc_access", "R_MICROSRVC_MAIN.msrvc_id = r_msrvc_access.object_id" },
        {"r_msrvc_access", "r_msrvc_tokn_accs",  "r_msrvc_access.access_typ_id = r_msrvc_tokn_accs.token_id" },
        {"r_msrvc_access", "r_msrvc_user_group", "r_msrvc_access.user_id = r_msrvc_user_group.group_user_id" },
        {"r_msrvc_user_group", "r_msrvc_user_main", "r_msrvc_user_group.user_id = r_msrvc_user_main.user_id" },
        {"R_MICROSRVC_MAIN", "r_msrvc_deny_access", "R_MICROSRVC_MAIN.msrvc_id = r_msrvc_deny_access.object_id" },
        {"r_msrvc_deny_access", "r_msrvc_tokn_deny_accs", "r_msrvc_deny_access.access_typ_id = r_msrvc_tokn_deny_accs.token_id" },
        {"r_msrvc_deny_access", "r_msrvc_da_user_group",     "r_msrvc_deny_access.user_id = r_msrvc_da_user_group.group_user_id" },
        {"r_msrvc_da_user_group", "r_msrvc_da_user_main", "r_msrvc_da_user_group.user_id = r_msrvc_da_user_main.user_id" },
        {"R_MICROSRVC_MAIN", "r_msrvc_audit", "R_MICROSRVC_MAIN.msrvc_id = r_msrvc_audit.object_id" },
        {"r_msrvc_audit", "r_msrvc_tokn_audit", "r_msrvc_audit.action_id = r_msrvc_tokn_audit.token_id" },
        {"r_msrvc_audit", "r_msrvc_au_user_group", "r_msrvc_audit.user_id = r_msrvc_au_user_group.group_user_id" },
        {"r_msrvc_au_user_group", "r_msrvc_au_user_main", "r_msrvc_au_user_group.user_id = r_msrvc_au_user_main.user_id" },

        {"R_TICKET_MAIN", "R_TICKET_ALLOWED_HOSTS", "R_TICKET_MAIN.ticket_id = R_TICKET_ALLOWED_HOSTS.ticket_id" },
        {"R_TICKET_MAIN", "R_TICKET_ALLOWED_USERS", "R_TICKET_MAIN.ticket_id = R_TICKET_ALLOWED_USERS.ticket_id" },
        {"R_TICKET_MAIN", "R_TICKET_ALLOWED_GROUPS", "R_TICKET_MAIN.ticket_id = R_TICKET_ALLOWED_GROUPS.ticket_id" },

        {"R_TICKET_MAIN", "R_DATA_MAIN", "R_TICKET_MAIN.object_id = R_DATA_MAIN.data_id" },
        {"R_TICKET_MAIN", "r_ticket_coll_main", "R_TICKET_MAIN.object_id = r_ticket_coll_main.coll_id" },
        {"R_TICKET_MAIN", "r_ticket_data_coll_main", "R_TICKET_MAIN.object_id = R_DATA_MAIN.data_id AND R_DATA_MAIN.coll_id = r_ticket_data_coll_main.coll_id" },
        {"R_TICKET_MAIN", "r_ticket_user_main", "R_TICKET_MAIN.user_id = r_ticket_user_main.user_id" }
    }; // foreign_key_link_map
} // namespace irods::experemental::api::genquery

#endif // IRODS_TABLE_COLUMN_KEY_MAPS_HPP
